// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: user/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误原因枚举
type ErrorReason int32

const (
	ErrorReason_USER_NOT_FOUND      ErrorReason = 0 // 用户不存在
	ErrorReason_USER_ALREADY_EXISTS ErrorReason = 1 // 用户已存在
	ErrorReason_INVALID_PASSWORD    ErrorReason = 2 // 密码错误
	ErrorReason_INVALID_TOKEN       ErrorReason = 3 // 令牌无效
	ErrorReason_USER_DISABLED       ErrorReason = 4 // 用户已禁用
	ErrorReason_SMS_CODE_INVALID    ErrorReason = 5 // 验证码无效
	ErrorReason_SMS_CODE_EXPIRED    ErrorReason = 6 // 验证码过期
	ErrorReason_SMS_SEND_LIMIT      ErrorReason = 7 // 短信发送频率限制
	ErrorReason_PASSWORD_LOCKED     ErrorReason = 8 // 密码错误次数过多被锁定
	ErrorReason_PERMISSION_DENIED   ErrorReason = 9 // 权限不足（无权操作该用户）
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "USER_NOT_FOUND",
		1: "USER_ALREADY_EXISTS",
		2: "INVALID_PASSWORD",
		3: "INVALID_TOKEN",
		4: "USER_DISABLED",
		5: "SMS_CODE_INVALID",
		6: "SMS_CODE_EXPIRED",
		7: "SMS_SEND_LIMIT",
		8: "PASSWORD_LOCKED",
		9: "PERMISSION_DENIED",
	}
	ErrorReason_value = map[string]int32{
		"USER_NOT_FOUND":      0,
		"USER_ALREADY_EXISTS": 1,
		"INVALID_PASSWORD":    2,
		"INVALID_TOKEN":       3,
		"USER_DISABLED":       4,
		"SMS_CODE_INVALID":    5,
		"SMS_CODE_EXPIRED":    6,
		"SMS_SEND_LIMIT":      7,
		"PASSWORD_LOCKED":     8,
		"PERMISSION_DENIED":   9,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_user_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_user_v1_user_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

// 1. 账号密码登录
type LoginByPwdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 账号：手机号/用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 密码（6-20位数字、字母、下划线）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByPwdRequest) Reset() {
	*x = LoginByPwdRequest{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByPwdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByPwdRequest) ProtoMessage() {}

func (x *LoginByPwdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByPwdRequest.ProtoReflect.Descriptor instead.
func (*LoginByPwdRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginByPwdRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginByPwdRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 2. 短信验证码登录（自动注册）
type LoginBySmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"` // 手机号（11位数字）
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`   // 短信验证码（6位数字）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginBySmsRequest) Reset() {
	*x = LoginBySmsRequest{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginBySmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginBySmsRequest) ProtoMessage() {}

func (x *LoginBySmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginBySmsRequest.ProtoReflect.Descriptor instead.
func (*LoginBySmsRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginBySmsRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginBySmsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 3. 注册（手机号+验证码+密码+邀请码）
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`           // 手机号（11位数字）
	SmsCode       string                 `protobuf:"bytes,2,opt,name=smsCode,proto3" json:"smsCode,omitempty"`       // 短信验证码（6位数字）
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`     // 密码（6-20位数字、字母、下划线）
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`     // 可选
	InviteCode    string                 `protobuf:"bytes,5,opt,name=inviteCode,proto3" json:"inviteCode,omitempty"` // 可选（邀请码）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

// 4. 注册返回（只返回ID）
type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 用户ID（唯一标识，数据库里的主键）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 5. 发送短信验证码
type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"` // 手机号（11位数字）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *SendSmsRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type SendSmsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Expire        int64                  `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`   // 过期时间（短信验证码多少秒后过期）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsReply) Reset() {
	*x = SendSmsReply{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsReply) ProtoMessage() {}

func (x *SendSmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsReply.ProtoReflect.Descriptor instead.
func (*SendSmsReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *SendSmsReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendSmsReply) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

// 6. 登录统一返回（只保留前8个）
type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                     // 用户ID（唯一标识，数据库里的主键）
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`         // 用户名（密码登录用的账号）
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`               // 手机号（脱敏展示，比如 138****1234）
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`         // 昵称（页面显示的名字）
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`             // 头像URL（前端显示头像）
	AccessToken   string                 `protobuf:"bytes,6,opt,name=accessToken,proto3" json:"accessToken,omitempty"`   // 访问令牌（调接口必须带，证明你登录了）
	RefreshToken  string                 `protobuf:"bytes,7,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"` // 刷新令牌（accessToken过期时，用它换新的）
	ExpiresIn     int64                  `protobuf:"varint,8,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`      // 过期时间（accessToken多少秒后过期）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *LoginReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoginReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReply) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LoginReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *LoginReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginReply) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 7. 刷新Token
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"` // 刷新令牌（accessToken过期时，用它换新的）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`   // 访问令牌（调接口必须带，证明你登录了）
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"` // 刷新令牌（accessToken过期时，用它换新的）
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expiresIn,proto3" json:"expiresIn,omitempty"`      // 过期时间（accessToken多少秒后过期）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReply) Reset() {
	*x = RefreshTokenReply{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReply) ProtoMessage() {}

func (x *RefreshTokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReply.ProtoReflect.Descriptor instead.
func (*RefreshTokenReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshTokenReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenReply) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 8. 退出登录
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"` // 刷新令牌（accessToken过期时，用它换新的）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_user_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 提示信息（成功/失败原因）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_user_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *LogoutReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogoutReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 9. 获取当前登录用户信息（不需要传id）
type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_user_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{11}
}

type GetMeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                  // 用户ID（唯一标识，数据库里的主键）
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`      // 用户名（密码登录用的账号）
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`            // 手机号（脱敏展示，比如 138****1234）
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`      // 昵称（页面显示的名字）
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`          // 头像URL（前端显示头像）
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`              // 用户角色（user/admin）
	CreateTime    int64                  `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime,omitempty"` // 创建时间（时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeReply) Reset() {
	*x = GetMeReply{}
	mi := &file_user_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeReply) ProtoMessage() {}

func (x *GetMeReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeReply.ProtoReflect.Descriptor instead.
func (*GetMeReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetMeReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMeReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetMeReply) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetMeReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetMeReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetMeReply) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetMeReply) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// 10. 获取指定用户信息（需要权限检查）
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 用户ID（唯一标识，数据库里的主键）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                  // 用户ID（唯一标识，数据库里的主键）
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`      // 用户名（密码登录用的账号）
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`            // 手机号（脱敏展示，比如 138****1234）
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`      // 昵称（页面显示的名字）
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`          // 头像URL（前端显示头像）
	CreateTime    int64                  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"` // 创建时间（时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReply) Reset() {
	*x = GetUserReply{}
	mi := &file_user_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReply) ProtoMessage() {}

func (x *GetUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReply.ProtoReflect.Descriptor instead.
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserReply) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserReply) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// 11. 更新用户信息（需要权限检查）
type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // 用户ID（唯一标识，数据库里的主键）
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"` //昵称（页面显示的名字）
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 头像URL（前端显示头像）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // 用户ID（唯一标识，数据库里的主键）
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"` // 昵称（页面显示的名字）
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 头像URL（前端显示头像）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReply) Reset() {
	*x = UpdateUserReply{}
	mi := &file_user_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReply) ProtoMessage() {}

func (x *UpdateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReply.ProtoReflect.Descriptor instead.
func (*UpdateUserReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateUserReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserReply) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 订单全字段
type OrderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                              // 订单ID
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                 // 租户ID
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                        // 用户ID
	OrderNo       string                 `protobuf:"bytes,4,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                     // 订单号
	Source        int32                  `protobuf:"varint,5,opt,name=source,proto3" json:"source,omitempty"`                                     // 来源 1=门票 2=共享单车 3=充电宝 4=智能快递柜
	OrderType     string                 `protobuf:"bytes,6,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`               // 订单类型
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                     // 状态 1=待支付 2=已支付 3=已完成 4=已取消 5=已退款
	TotalAmount   int32                  `protobuf:"varint,8,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`        // 金额（分）
	Currency      string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`                                  // 币种
	PaymentMethod int32                  `protobuf:"varint,10,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // 支付方式 0=未支付 1=微信 2=支付宝 3=钱包余额
	Title         string                 `protobuf:"bytes,11,opt,name=title,proto3" json:"title,omitempty"`                                       // 订单标题
	Description   string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`                           // 订单描述
	ExtraJson     string                 `protobuf:"bytes,13,opt,name=extra_json,json=extraJson,proto3" json:"extra_json,omitempty"`              // 扩展字段（JSON）
	PaidAt        int64                  `protobuf:"varint,14,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`                      // 支付时间（时间戳）
	CreatedAt     int64                  `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`             // 创建时间（时间戳）
	UpdatedAt     int64                  `protobuf:"varint,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`             // 更新时间（时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_user_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *OrderInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderInfo) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *OrderInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderInfo) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderInfo) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *OrderInfo) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *OrderInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderInfo) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *OrderInfo) GetPaymentMethod() int32 {
	if x != nil {
		return x.PaymentMethod
	}
	return 0
}

func (x *OrderInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OrderInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrderInfo) GetExtraJson() string {
	if x != nil {
		return x.ExtraJson
	}
	return ""
}

func (x *OrderInfo) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

func (x *OrderInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OrderInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 创建订单
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        int32                  `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`                              // 来源
	OrderType     string                 `protobuf:"bytes,2,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`        // 订单类型
	TotalAmount   int32                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"` // 金额（分）
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`                           // 币种
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`                                 // 订单标题
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`                     // 订单描述
	ExtraJson     string                 `protobuf:"bytes,7,opt,name=extra_json,json=extraJson,proto3" json:"extra_json,omitempty"`        // 扩展字段（JSON）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_user_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *CreateOrderRequest) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *CreateOrderRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *CreateOrderRequest) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreateOrderRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrderRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateOrderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateOrderRequest) GetExtraJson() string {
	if x != nil {
		return x.ExtraJson
	}
	return ""
}

type CreateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_user_v1_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{19}
}

func (x *CreateOrderReply) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

// 查询单个订单
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"` // 订单号（路径参数）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_user_v1_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{20}
}

func (x *GetOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReply) Reset() {
	*x = GetOrderReply{}
	mi := &file_user_v1_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReply) ProtoMessage() {}

func (x *GetOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReply.ProtoReflect.Descriptor instead.
func (*GetOrderReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{21}
}

func (x *GetOrderReply) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

// 订单列表查询
type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAfter  string                 `protobuf:"bytes,1,opt,name=created_after,json=createdAfter,proto3" json:"created_after,omitempty"`     // 创建时间起始
	CreatedBefore string                 `protobuf:"bytes,2,opt,name=created_before,json=createdBefore,proto3" json:"created_before,omitempty"`  // 创建时间截止
	Source        int32                  `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`                                    // 来源筛选
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                                    // 状态筛选
	MinAmount     int32                  `protobuf:"varint,5,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`             // 最小金额
	MaxAmount     int32                  `protobuf:"varint,6,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`             // 最大金额
	PaymentMethod int32                  `protobuf:"varint,7,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // 支付方式筛选
	Limit         int32                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`                                      // 每页数量
	Cursor        string                 `protobuf:"bytes,9,opt,name=cursor,proto3" json:"cursor,omitempty"`                                     // 游标
	SortField     string                 `protobuf:"bytes,10,opt,name=sort_field,json=sortField,proto3" json:"sort_field,omitempty"`             // 排序字段
	SortDirection string                 `protobuf:"bytes,11,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"` // 排序方向 asc/desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_user_v1_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{22}
}

func (x *ListOrdersRequest) GetCreatedAfter() string {
	if x != nil {
		return x.CreatedAfter
	}
	return ""
}

func (x *ListOrdersRequest) GetCreatedBefore() string {
	if x != nil {
		return x.CreatedBefore
	}
	return ""
}

func (x *ListOrdersRequest) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *ListOrdersRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListOrdersRequest) GetMinAmount() int32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *ListOrdersRequest) GetMaxAmount() int32 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *ListOrdersRequest) GetPaymentMethod() int32 {
	if x != nil {
		return x.PaymentMethod
	}
	return 0
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListOrdersRequest) GetSortField() string {
	if x != nil {
		return x.SortField
	}
	return ""
}

func (x *ListOrdersRequest) GetSortDirection() string {
	if x != nil {
		return x.SortDirection
	}
	return ""
}

type ListOrdersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderInfo           `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersReply) Reset() {
	*x = ListOrdersReply{}
	mi := &file_user_v1_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersReply) ProtoMessage() {}

func (x *ListOrdersReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersReply.ProtoReflect.Descriptor instead.
func (*ListOrdersReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{23}
}

func (x *ListOrdersReply) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersReply) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListOrdersReply) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListOrdersReply) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 取消订单
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"` // 订单号（路径参数）
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                  // 取消原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_user_v1_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{24}
}

func (x *CancelOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CancelOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *OrderInfo             `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReply) Reset() {
	*x = CancelOrderReply{}
	mi := &file_user_v1_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReply) ProtoMessage() {}

func (x *CancelOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReply.ProtoReflect.Descriptor instead.
func (*CancelOrderReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{25}
}

func (x *CancelOrderReply) GetOrder() *OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

// 发起支付
type PayOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`                    // 订单号（路径参数）
	PaymentMethod int32                  `protobuf:"varint,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // 支付方式 1=微信 2=支付宝 3=钱包余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderRequest) Reset() {
	*x = PayOrderRequest{}
	mi := &file_user_v1_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderRequest) ProtoMessage() {}

func (x *PayOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderRequest.ProtoReflect.Descriptor instead.
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{26}
}

func (x *PayOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PayOrderRequest) GetPaymentMethod() int32 {
	if x != nil {
		return x.PaymentMethod
	}
	return 0
}

type PayOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`       // 订单号
	PayParams     string                 `protobuf:"bytes,2,opt,name=pay_params,json=payParams,proto3" json:"pay_params,omitempty"` // 支付参数（JSON，前端拉起支付）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderReply) Reset() {
	*x = PayOrderReply{}
	mi := &file_user_v1_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderReply) ProtoMessage() {}

func (x *PayOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderReply.ProtoReflect.Descriptor instead.
func (*PayOrderReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{27}
}

func (x *PayOrderReply) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PayOrderReply) GetPayParams() string {
	if x != nil {
		return x.PayParams
	}
	return ""
}

// 支付回调
type CallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"` // 支付渠道（路径参数）
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`       // 回调原始数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackRequest) Reset() {
	*x = CallbackRequest{}
	mi := &file_user_v1_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRequest) ProtoMessage() {}

func (x *CallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRequest.ProtoReflect.Descriptor instead.
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{28}
}

func (x *CallbackRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CallbackRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CallbackReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackReply) Reset() {
	*x = CallbackReply{}
	mi := &file_user_v1_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackReply) ProtoMessage() {}

func (x *CallbackReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackReply.ProtoReflect.Descriptor instead.
func (*CallbackReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{29}
}

func (x *CallbackReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CallbackReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 柜格信息
type GridInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                           // 柜格ID
	StationId     int64                  `protobuf:"varint,2,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`            // 站点ID
	GridNo        string                 `protobuf:"bytes,3,opt,name=grid_no,json=gridNo,proto3" json:"grid_no,omitempty"`                      // 柜格编号（如 A-01）
	GridType      string                 `protobuf:"bytes,4,opt,name=grid_type,json=gridType,proto3" json:"grid_type,omitempty"`                // 柜格类型: small/medium/large
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`                                   // 状态: 1=空闲 2=占用 3=预留 4=故障
	PricePerHour  int32                  `protobuf:"varint,6,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"` // 每小时价格（分）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridInfo) Reset() {
	*x = GridInfo{}
	mi := &file_user_v1_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridInfo) ProtoMessage() {}

func (x *GridInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridInfo.ProtoReflect.Descriptor instead.
func (*GridInfo) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{30}
}

func (x *GridInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GridInfo) GetStationId() int64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *GridInfo) GetGridNo() string {
	if x != nil {
		return x.GridNo
	}
	return ""
}

func (x *GridInfo) GetGridType() string {
	if x != nil {
		return x.GridType
	}
	return ""
}

func (x *GridInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GridInfo) GetPricePerHour() int32 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

// 站点信息
type StationInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                // 站点ID
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                             // 站点名称
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                       // 详细地址
	Lat            float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`                                             // 纬度
	Lng            float64                `protobuf:"fixed64,5,opt,name=lng,proto3" json:"lng,omitempty"`                                             // 经度
	Province       string                 `protobuf:"bytes,6,opt,name=province,proto3" json:"province,omitempty"`                                     // 省
	City           string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`                                             // 市
	District       string                 `protobuf:"bytes,8,opt,name=district,proto3" json:"district,omitempty"`                                     // 区
	Status         int32                  `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`                                        // 状态
	Distance       int32                  `protobuf:"varint,10,opt,name=distance,proto3" json:"distance,omitempty"`                                   // 距离（米，仅搜索时有值）
	AvailableGrids int32                  `protobuf:"varint,11,opt,name=available_grids,json=availableGrids,proto3" json:"available_grids,omitempty"` // 空闲柜格数
	TotalGrids     int32                  `protobuf:"varint,12,opt,name=total_grids,json=totalGrids,proto3" json:"total_grids,omitempty"`             // 总柜格数
	MinPrice       int32                  `protobuf:"varint,13,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`                   // 最低价格（分/小时）
	Grids          []*GridInfo            `protobuf:"bytes,14,rep,name=grids,proto3" json:"grids,omitempty"`                                          // 柜格列表（仅详情接口返回）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StationInfo) Reset() {
	*x = StationInfo{}
	mi := &file_user_v1_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationInfo) ProtoMessage() {}

func (x *StationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationInfo.ProtoReflect.Descriptor instead.
func (*StationInfo) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{31}
}

func (x *StationInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StationInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StationInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *StationInfo) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *StationInfo) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *StationInfo) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *StationInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *StationInfo) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *StationInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StationInfo) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *StationInfo) GetAvailableGrids() int32 {
	if x != nil {
		return x.AvailableGrids
	}
	return 0
}

func (x *StationInfo) GetTotalGrids() int32 {
	if x != nil {
		return x.TotalGrids
	}
	return 0
}

func (x *StationInfo) GetMinPrice() int32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *StationInfo) GetGrids() []*GridInfo {
	if x != nil {
		return x.Grids
	}
	return nil
}

// 搜索附近站点
type SearchNearbyStationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lng           string                 `protobuf:"bytes,1,opt,name=lng,proto3" json:"lng,omitempty"`           // 经度
	Lat           string                 `protobuf:"bytes,2,opt,name=lat,proto3" json:"lat,omitempty"`           // 纬度
	Radius        int32                  `protobuf:"varint,3,opt,name=radius,proto3" json:"radius,omitempty"`    // 搜索半径（米），默认3000
	Keywords      string                 `protobuf:"bytes,4,opt,name=keywords,proto3" json:"keywords,omitempty"` // 搜索关键词（可选，如"快递柜"）
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`      // 返回数量，默认20，最大50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchNearbyStationsRequest) Reset() {
	*x = SearchNearbyStationsRequest{}
	mi := &file_user_v1_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNearbyStationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNearbyStationsRequest) ProtoMessage() {}

func (x *SearchNearbyStationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNearbyStationsRequest.ProtoReflect.Descriptor instead.
func (*SearchNearbyStationsRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{32}
}

func (x *SearchNearbyStationsRequest) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

func (x *SearchNearbyStationsRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *SearchNearbyStationsRequest) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *SearchNearbyStationsRequest) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *SearchNearbyStationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchNearbyStationsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stations      []*StationInfo         `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchNearbyStationsReply) Reset() {
	*x = SearchNearbyStationsReply{}
	mi := &file_user_v1_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchNearbyStationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchNearbyStationsReply) ProtoMessage() {}

func (x *SearchNearbyStationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchNearbyStationsReply.ProtoReflect.Descriptor instead.
func (*SearchNearbyStationsReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{33}
}

func (x *SearchNearbyStationsReply) GetStations() []*StationInfo {
	if x != nil {
		return x.Stations
	}
	return nil
}

func (x *SearchNearbyStationsReply) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 获取站点详情
type GetStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     int64                  `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"` // 站点ID（路径参数）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStationRequest) Reset() {
	*x = GetStationRequest{}
	mi := &file_user_v1_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationRequest) ProtoMessage() {}

func (x *GetStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationRequest.ProtoReflect.Descriptor instead.
func (*GetStationRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{34}
}

func (x *GetStationRequest) GetStationId() int64 {
	if x != nil {
		return x.StationId
	}
	return 0
}

type GetStationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Station       *StationInfo           `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStationReply) Reset() {
	*x = GetStationReply{}
	mi := &file_user_v1_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationReply) ProtoMessage() {}

func (x *GetStationReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationReply.ProtoReflect.Descriptor instead.
func (*GetStationReply) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{35}
}

func (x *GetStationReply) GetStation() *StationInfo {
	if x != nil {
		return x.Station
	}
	return nil
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\vapi.user.v1\x1a\x1cgoogle/api/annotations.proto\"K\n" +
	"\x11LoginByPwdRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"=\n" +
	"\x11LoginBySmsRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x99\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x18\n" +
	"\asmsCode\x18\x02 \x01(\tR\asmsCode\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x1e\n" +
	"\n" +
	"inviteCode\x18\x05 \x01(\tR\n" +
	"inviteCode\"\x1f\n" +
	"\rRegisterReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x0eSendSmsRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"@\n" +
	"\fSendSmsReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06expire\x18\x02 \x01(\x03R\x06expire\"\xe6\x01\n" +
	"\n" +
	"LoginReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12 \n" +
	"\vaccessToken\x18\x06 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\a \x01(\tR\frefreshToken\x12\x1c\n" +
	"\texpiresIn\x18\b \x01(\x03R\texpiresIn\"9\n" +
	"\x13RefreshTokenRequest\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\"w\n" +
	"\x11RefreshTokenReply\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12\x1c\n" +
	"\texpiresIn\x18\x03 \x01(\x03R\texpiresIn\"3\n" +
	"\rLogoutRequest\x12\"\n" +
	"\frefreshToken\x18\x01 \x01(\tR\frefreshToken\"A\n" +
	"\vLogoutReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0e\n" +
	"\fGetMeRequest\"\xb6\x01\n" +
	"\n" +
	"GetMeReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x1e\n" +
	"\n" +
	"createTime\x18\a \x01(\x03R\n" +
	"createTime\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa4\x01\n" +
	"\fGetUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x1e\n" +
	"\n" +
	"createTime\x18\x06 \x01(\x03R\n" +
	"createTime\"W\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"U\n" +
	"\x0fUpdateUserReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"\xcf\x03\n" +
	"\tOrderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\border_no\x18\x04 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06source\x18\x05 \x01(\x05R\x06source\x12\x1d\n" +
	"\n" +
	"order_type\x18\x06 \x01(\tR\torderType\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12!\n" +
	"\ftotal_amount\x18\b \x01(\x05R\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\n" +
	" \x01(\x05R\rpaymentMethod\x12\x14\n" +
	"\x05title\x18\v \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"extra_json\x18\r \x01(\tR\textraJson\x12\x17\n" +
	"\apaid_at\x18\x0e \x01(\x03R\x06paidAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\x03R\tupdatedAt\"\xe1\x01\n" +
	"\x12CreateOrderRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\x05R\x06source\x12\x1d\n" +
	"\n" +
	"order_type\x18\x02 \x01(\tR\torderType\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x05R\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"extra_json\x18\a \x01(\tR\textraJson\"@\n" +
	"\x10CreateOrderReply\x12,\n" +
	"\x05order\x18\x01 \x01(\v2\x16.api.user.v1.OrderInfoR\x05order\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"=\n" +
	"\rGetOrderReply\x12,\n" +
	"\x05order\x18\x01 \x01(\v2\x16.api.user.v1.OrderInfoR\x05order\"\xe8\x02\n" +
	"\x11ListOrdersRequest\x12#\n" +
	"\rcreated_after\x18\x01 \x01(\tR\fcreatedAfter\x12%\n" +
	"\x0ecreated_before\x18\x02 \x01(\tR\rcreatedBefore\x12\x16\n" +
	"\x06source\x18\x03 \x01(\x05R\x06source\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x05 \x01(\x05R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x06 \x01(\x05R\tmaxAmount\x12%\n" +
	"\x0epayment_method\x18\a \x01(\x05R\rpaymentMethod\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\t \x01(\tR\x06cursor\x12\x1d\n" +
	"\n" +
	"sort_field\x18\n" +
	" \x01(\tR\tsortField\x12%\n" +
	"\x0esort_direction\x18\v \x01(\tR\rsortDirection\"\x9e\x01\n" +
	"\x0fListOrdersReply\x12.\n" +
	"\x06orders\x18\x01 \x03(\v2\x16.api.user.v1.OrderInfoR\x06orders\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\"G\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"@\n" +
	"\x10CancelOrderReply\x12,\n" +
	"\x05order\x18\x01 \x01(\v2\x16.api.user.v1.OrderInfoR\x05order\"S\n" +
	"\x0fPayOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\x05R\rpaymentMethod\"I\n" +
	"\rPayOrderReply\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"pay_params\x18\x02 \x01(\tR\tpayParams\"?\n" +
	"\x0fCallbackRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"C\n" +
	"\rCallbackReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xad\x01\n" +
	"\bGridInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"station_id\x18\x02 \x01(\x03R\tstationId\x12\x17\n" +
	"\agrid_no\x18\x03 \x01(\tR\x06gridNo\x12\x1b\n" +
	"\tgrid_type\x18\x04 \x01(\tR\bgridType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12$\n" +
	"\x0eprice_per_hour\x18\x06 \x01(\x05R\fpricePerHour\"\x83\x03\n" +
	"\vStationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x05 \x01(\x01R\x03lng\x12\x1a\n" +
	"\bprovince\x18\x06 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\b \x01(\tR\bdistrict\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12\x1a\n" +
	"\bdistance\x18\n" +
	" \x01(\x05R\bdistance\x12'\n" +
	"\x0favailable_grids\x18\v \x01(\x05R\x0eavailableGrids\x12\x1f\n" +
	"\vtotal_grids\x18\f \x01(\x05R\n" +
	"totalGrids\x12\x1b\n" +
	"\tmin_price\x18\r \x01(\x05R\bminPrice\x12+\n" +
	"\x05grids\x18\x0e \x03(\v2\x15.api.user.v1.GridInfoR\x05grids\"\x8b\x01\n" +
	"\x1bSearchNearbyStationsRequest\x12\x10\n" +
	"\x03lng\x18\x01 \x01(\tR\x03lng\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\tR\x03lat\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x05R\x06radius\x12\x1a\n" +
	"\bkeywords\x18\x04 \x01(\tR\bkeywords\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"r\n" +
	"\x19SearchNearbyStationsReply\x124\n" +
	"\bstations\x18\x01 \x03(\v2\x18.api.user.v1.StationInfoR\bstations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"2\n" +
	"\x11GetStationRequest\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\x03R\tstationId\"E\n" +
	"\x0fGetStationReply\x122\n" +
	"\astation\x18\x01 \x01(\v2\x18.api.user.v1.StationInfoR\astation*\xe2\x01\n" +
	"\vErrorReason\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\x00\x12\x17\n" +
	"\x13USER_ALREADY_EXISTS\x10\x01\x12\x14\n" +
	"\x10INVALID_PASSWORD\x10\x02\x12\x11\n" +
	"\rINVALID_TOKEN\x10\x03\x12\x11\n" +
	"\rUSER_DISABLED\x10\x04\x12\x14\n" +
	"\x10SMS_CODE_INVALID\x10\x05\x12\x14\n" +
	"\x10SMS_CODE_EXPIRED\x10\x06\x12\x12\n" +
	"\x0eSMS_SEND_LIMIT\x10\a\x12\x13\n" +
	"\x0fPASSWORD_LOCKED\x10\b\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\t2\xe6\r\n" +
	"\vUserService\x12b\n" +
	"\bRegister\x12\x1c.api.user.v1.RegisterRequest\x1a\x1a.api.user.v1.RegisterReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/user/register\x12[\n" +
	"\x05Login\x12\x1e.api.user.v1.LoginByPwdRequest\x1a\x17.api.user.v1.LoginReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/user/login\x12c\n" +
	"\vSendSmsCode\x12\x1b.api.user.v1.SendSmsRequest\x1a\x19.api.user.v1.SendSmsReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/user/sms/send\x12d\n" +
	"\n" +
	"LoginBySms\x12\x1e.api.user.v1.LoginBySmsRequest\x1a\x17.api.user.v1.LoginReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/user/login/sms\x12l\n" +
	"\fRefreshToken\x12 .api.user.v1.RefreshTokenRequest\x1a\x17.api.user.v1.LoginReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/user/token/refresh\x12K\n" +
	"\x05GetMe\x12\x19.api.user.v1.GetMeRequest\x1a\x17.api.user.v1.GetMeReply\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/v1/me\x12X\n" +
	"\aGetUser\x12\x1b.api.user.v1.GetUserRequest\x1a\x19.api.user.v1.GetUserReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/user/{id}\x12d\n" +
	"\n" +
	"UpdateUser\x12\x1e.api.user.v1.UpdateUserRequest\x1a\x1c.api.user.v1.UpdateUserReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/v1/user/{id}\x12Z\n" +
	"\x06Logout\x12\x1a.api.user.v1.LogoutRequest\x1a\x18.api.user.v1.LogoutReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/user/logout\x12c\n" +
	"\vCreateOrder\x12\x1f.api.user.v1.CreateOrderRequest\x1a\x1d.api.user.v1.CreateOrderReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/order\x12b\n" +
	"\bGetOrder\x12\x1c.api.user.v1.GetOrderRequest\x1a\x1a.api.user.v1.GetOrderReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/order/{order_no}\x12^\n" +
	"\n" +
	"ListOrders\x12\x1e.api.user.v1.ListOrdersRequest\x1a\x1c.api.user.v1.ListOrdersReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/orders\x12u\n" +
	"\vCancelOrder\x12\x1f.api.user.v1.CancelOrderRequest\x1a\x1d.api.user.v1.CancelOrderReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/order/{order_no}/cancel\x12i\n" +
	"\bPayOrder\x12\x1c.api.user.v1.PayOrderRequest\x1a\x1a.api.user.v1.PayOrderReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/order/{order_no}/pay\x12s\n" +
	"\x0eHandleCallback\x12\x1c.api.user.v1.CallbackRequest\x1a\x1a.api.user.v1.CallbackReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/order/callback/{channel}\x12\x85\x01\n" +
	"\x14SearchNearbyStations\x12(.api.user.v1.SearchNearbyStationsRequest\x1a&.api.user.v1.SearchNearbyStationsReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/stations/nearby\x12l\n" +
	"\n" +
	"GetStation\x12\x1e.api.user.v1.GetStationRequest\x1a\x1c.api.user.v1.GetStationReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/station/{station_id}B#Z!shared-device-saas/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_user_v1_user_proto_goTypes = []any{
	(ErrorReason)(0),                    // 0: api.user.v1.ErrorReason
	(*LoginByPwdRequest)(nil),           // 1: api.user.v1.LoginByPwdRequest
	(*LoginBySmsRequest)(nil),           // 2: api.user.v1.LoginBySmsRequest
	(*RegisterRequest)(nil),             // 3: api.user.v1.RegisterRequest
	(*RegisterReply)(nil),               // 4: api.user.v1.RegisterReply
	(*SendSmsRequest)(nil),              // 5: api.user.v1.SendSmsRequest
	(*SendSmsReply)(nil),                // 6: api.user.v1.SendSmsReply
	(*LoginReply)(nil),                  // 7: api.user.v1.LoginReply
	(*RefreshTokenRequest)(nil),         // 8: api.user.v1.RefreshTokenRequest
	(*RefreshTokenReply)(nil),           // 9: api.user.v1.RefreshTokenReply
	(*LogoutRequest)(nil),               // 10: api.user.v1.LogoutRequest
	(*LogoutReply)(nil),                 // 11: api.user.v1.LogoutReply
	(*GetMeRequest)(nil),                // 12: api.user.v1.GetMeRequest
	(*GetMeReply)(nil),                  // 13: api.user.v1.GetMeReply
	(*GetUserRequest)(nil),              // 14: api.user.v1.GetUserRequest
	(*GetUserReply)(nil),                // 15: api.user.v1.GetUserReply
	(*UpdateUserRequest)(nil),           // 16: api.user.v1.UpdateUserRequest
	(*UpdateUserReply)(nil),             // 17: api.user.v1.UpdateUserReply
	(*OrderInfo)(nil),                   // 18: api.user.v1.OrderInfo
	(*CreateOrderRequest)(nil),          // 19: api.user.v1.CreateOrderRequest
	(*CreateOrderReply)(nil),            // 20: api.user.v1.CreateOrderReply
	(*GetOrderRequest)(nil),             // 21: api.user.v1.GetOrderRequest
	(*GetOrderReply)(nil),               // 22: api.user.v1.GetOrderReply
	(*ListOrdersRequest)(nil),           // 23: api.user.v1.ListOrdersRequest
	(*ListOrdersReply)(nil),             // 24: api.user.v1.ListOrdersReply
	(*CancelOrderRequest)(nil),          // 25: api.user.v1.CancelOrderRequest
	(*CancelOrderReply)(nil),            // 26: api.user.v1.CancelOrderReply
	(*PayOrderRequest)(nil),             // 27: api.user.v1.PayOrderRequest
	(*PayOrderReply)(nil),               // 28: api.user.v1.PayOrderReply
	(*CallbackRequest)(nil),             // 29: api.user.v1.CallbackRequest
	(*CallbackReply)(nil),               // 30: api.user.v1.CallbackReply
	(*GridInfo)(nil),                    // 31: api.user.v1.GridInfo
	(*StationInfo)(nil),                 // 32: api.user.v1.StationInfo
	(*SearchNearbyStationsRequest)(nil), // 33: api.user.v1.SearchNearbyStationsRequest
	(*SearchNearbyStationsReply)(nil),   // 34: api.user.v1.SearchNearbyStationsReply
	(*GetStationRequest)(nil),           // 35: api.user.v1.GetStationRequest
	(*GetStationReply)(nil),             // 36: api.user.v1.GetStationReply
}
var file_user_v1_user_proto_depIdxs = []int32{
	18, // 0: api.user.v1.CreateOrderReply.order:type_name -> api.user.v1.OrderInfo
	18, // 1: api.user.v1.GetOrderReply.order:type_name -> api.user.v1.OrderInfo
	18, // 2: api.user.v1.ListOrdersReply.orders:type_name -> api.user.v1.OrderInfo
	18, // 3: api.user.v1.CancelOrderReply.order:type_name -> api.user.v1.OrderInfo
	31, // 4: api.user.v1.StationInfo.grids:type_name -> api.user.v1.GridInfo
	32, // 5: api.user.v1.SearchNearbyStationsReply.stations:type_name -> api.user.v1.StationInfo
	32, // 6: api.user.v1.GetStationReply.station:type_name -> api.user.v1.StationInfo
	3,  // 7: api.user.v1.UserService.Register:input_type -> api.user.v1.RegisterRequest
	1,  // 8: api.user.v1.UserService.Login:input_type -> api.user.v1.LoginByPwdRequest
	5,  // 9: api.user.v1.UserService.SendSmsCode:input_type -> api.user.v1.SendSmsRequest
	2,  // 10: api.user.v1.UserService.LoginBySms:input_type -> api.user.v1.LoginBySmsRequest
	8,  // 11: api.user.v1.UserService.RefreshToken:input_type -> api.user.v1.RefreshTokenRequest
	12, // 12: api.user.v1.UserService.GetMe:input_type -> api.user.v1.GetMeRequest
	14, // 13: api.user.v1.UserService.GetUser:input_type -> api.user.v1.GetUserRequest
	16, // 14: api.user.v1.UserService.UpdateUser:input_type -> api.user.v1.UpdateUserRequest
	10, // 15: api.user.v1.UserService.Logout:input_type -> api.user.v1.LogoutRequest
	19, // 16: api.user.v1.UserService.CreateOrder:input_type -> api.user.v1.CreateOrderRequest
	21, // 17: api.user.v1.UserService.GetOrder:input_type -> api.user.v1.GetOrderRequest
	23, // 18: api.user.v1.UserService.ListOrders:input_type -> api.user.v1.ListOrdersRequest
	25, // 19: api.user.v1.UserService.CancelOrder:input_type -> api.user.v1.CancelOrderRequest
	27, // 20: api.user.v1.UserService.PayOrder:input_type -> api.user.v1.PayOrderRequest
	29, // 21: api.user.v1.UserService.HandleCallback:input_type -> api.user.v1.CallbackRequest
	33, // 22: api.user.v1.UserService.SearchNearbyStations:input_type -> api.user.v1.SearchNearbyStationsRequest
	35, // 23: api.user.v1.UserService.GetStation:input_type -> api.user.v1.GetStationRequest
	4,  // 24: api.user.v1.UserService.Register:output_type -> api.user.v1.RegisterReply
	7,  // 25: api.user.v1.UserService.Login:output_type -> api.user.v1.LoginReply
	6,  // 26: api.user.v1.UserService.SendSmsCode:output_type -> api.user.v1.SendSmsReply
	7,  // 27: api.user.v1.UserService.LoginBySms:output_type -> api.user.v1.LoginReply
	7,  // 28: api.user.v1.UserService.RefreshToken:output_type -> api.user.v1.LoginReply
	13, // 29: api.user.v1.UserService.GetMe:output_type -> api.user.v1.GetMeReply
	15, // 30: api.user.v1.UserService.GetUser:output_type -> api.user.v1.GetUserReply
	17, // 31: api.user.v1.UserService.UpdateUser:output_type -> api.user.v1.UpdateUserReply
	11, // 32: api.user.v1.UserService.Logout:output_type -> api.user.v1.LogoutReply
	20, // 33: api.user.v1.UserService.CreateOrder:output_type -> api.user.v1.CreateOrderReply
	22, // 34: api.user.v1.UserService.GetOrder:output_type -> api.user.v1.GetOrderReply
	24, // 35: api.user.v1.UserService.ListOrders:output_type -> api.user.v1.ListOrdersReply
	26, // 36: api.user.v1.UserService.CancelOrder:output_type -> api.user.v1.CancelOrderReply
	28, // 37: api.user.v1.UserService.PayOrder:output_type -> api.user.v1.PayOrderReply
	30, // 38: api.user.v1.UserService.HandleCallback:output_type -> api.user.v1.CallbackReply
	34, // 39: api.user.v1.UserService.SearchNearbyStations:output_type -> api.user.v1.SearchNearbyStationsReply
	36, // 40: api.user.v1.UserService.GetStation:output_type -> api.user.v1.GetStationReply
	24, // [24:41] is the sub-list for method output_type
	7,  // [7:24] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		EnumInfos:         file_user_v1_user_proto_enumTypes,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
