// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: user/v1/user.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserServiceGetUserById = "/api.user.v1.UserService/GetUserById"
const OperationUserServiceGetUserMe = "/api.user.v1.UserService/GetUserMe"
const OperationUserServiceLogin = "/api.user.v1.UserService/Login"
const OperationUserServiceLoginBySms = "/api.user.v1.UserService/LoginBySms"
const OperationUserServiceLogout = "/api.user.v1.UserService/Logout"
const OperationUserServiceRefreshToken = "/api.user.v1.UserService/RefreshToken"
const OperationUserServiceRegister = "/api.user.v1.UserService/Register"
const OperationUserServiceSendSmsCode = "/api.user.v1.UserService/SendSmsCode"
const OperationUserServiceUpdateProfile = "/api.user.v1.UserService/UpdateProfile"
const OperationUserServiceUpdateUserById = "/api.user.v1.UserService/UpdateUserById"
const OperationUserServiceUpdateUserMe = "/api.user.v1.UserService/UpdateUserMe"

type UserServiceHTTPServer interface {
	// GetUserById 获取指定用户信息（管理员操作他人，需要权限检查）
	GetUserById(context.Context, *GetUserByIdRequest) (*GetUserByIdReply, error)
	// GetUserMe 获取当前登录用户信息（普通用户操作自己，从Token解析）
	GetUserMe(context.Context, *GetUserMeRequest) (*GetUserMeReply, error)
	// Login 登录（账号 + 密码）
	Login(context.Context, *LoginByPwdRequest) (*LoginReply, error)
	// LoginBySms 短信验证码登录（自动注册）
	LoginBySms(context.Context, *LoginBySmsRequest) (*LoginReply, error)
	// Logout 退出登录
	Logout(context.Context, *LogoutRequest) (*LogoutReply, error)
	// RefreshToken 刷新 Token
	RefreshToken(context.Context, *RefreshTokenRequest) (*LoginReply, error)
	// Register 注册（手机号 + 验证码 + 密码）
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	// SendSmsCode 发送短信验证码
	SendSmsCode(context.Context, *SendSmsRequest) (*SendSmsReply, error)
	// UpdateProfile 部分更新个人信息（邮箱等，从Token解析）
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileReply, error)
	// UpdateUserById 部分更新指定用户信息（管理员操作他人，需要权限检查）
	UpdateUserById(context.Context, *UpdateUserByIdRequest) (*UpdateUserByIdReply, error)
	// UpdateUserMe 部分更新当前登录用户信息（普通用户修改自己，从Token解析）
	UpdateUserMe(context.Context, *UpdateUserMeRequest) (*UpdateUserMeReply, error)
}

func RegisterUserServiceHTTPServer(s *http.Server, srv UserServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/user/register", _UserService_Register0_HTTP_Handler(srv))
	r.POST("/v1/user/login", _UserService_Login0_HTTP_Handler(srv))
	r.POST("/v1/user/sms/send", _UserService_SendSmsCode0_HTTP_Handler(srv))
	r.POST("/v1/user/login/sms", _UserService_LoginBySms0_HTTP_Handler(srv))
	r.POST("/v1/user/token/refresh", _UserService_RefreshToken0_HTTP_Handler(srv))
	r.GET("/v1/user/me", _UserService_GetUserMe0_HTTP_Handler(srv))
	r.PATCH("/v1/user/me", _UserService_UpdateUserMe0_HTTP_Handler(srv))
	r.GET("/v1/user/{id}", _UserService_GetUserById0_HTTP_Handler(srv))
	r.PATCH("/v1/user/{id}", _UserService_UpdateUserById0_HTTP_Handler(srv))
	r.PATCH("/v1/user/profile", _UserService_UpdateProfile0_HTTP_Handler(srv))
	r.POST("/v1/user/logout", _UserService_Logout0_HTTP_Handler(srv))
}

func _UserService_Register0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceRegister)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Register(ctx, req.(*RegisterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RegisterReply)
		return ctx.Result(200, reply)
	}
}

func _UserService_Login0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginByPwdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginByPwdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _UserService_SendSmsCode0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendSmsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceSendSmsCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendSmsCode(ctx, req.(*SendSmsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendSmsReply)
		return ctx.Result(200, reply)
	}
}

func _UserService_LoginBySms0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginBySmsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceLoginBySms)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginBySms(ctx, req.(*LoginBySmsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _UserService_RefreshToken0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RefreshTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceRefreshToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RefreshToken(ctx, req.(*RefreshTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

func _UserService_GetUserMe0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserMeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceGetUserMe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserMe(ctx, req.(*GetUserMeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserMeReply)
		return ctx.Result(200, reply)
	}
}

func _UserService_UpdateUserMe0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserMeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceUpdateUserMe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserMe(ctx, req.(*UpdateUserMeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateUserMeReply)
		return ctx.Result(200, reply)
	}
}

func _UserService_GetUserById0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserByIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceGetUserById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserById(ctx, req.(*GetUserByIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserByIdReply)
		return ctx.Result(200, reply)
	}
}

func _UserService_UpdateUserById0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserByIdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceUpdateUserById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserById(ctx, req.(*UpdateUserByIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateUserByIdReply)
		return ctx.Result(200, reply)
	}
}

func _UserService_UpdateProfile0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceUpdateProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProfile(ctx, req.(*UpdateProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateProfileReply)
		return ctx.Result(200, reply)
	}
}

func _UserService_Logout0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LogoutRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceLogout)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Logout(ctx, req.(*LogoutRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LogoutReply)
		return ctx.Result(200, reply)
	}
}

type UserServiceHTTPClient interface {
	// GetUserById 获取指定用户信息（管理员操作他人，需要权限检查）
	GetUserById(ctx context.Context, req *GetUserByIdRequest, opts ...http.CallOption) (rsp *GetUserByIdReply, err error)
	// GetUserMe 获取当前登录用户信息（普通用户操作自己，从Token解析）
	GetUserMe(ctx context.Context, req *GetUserMeRequest, opts ...http.CallOption) (rsp *GetUserMeReply, err error)
	// Login 登录（账号 + 密码）
	Login(ctx context.Context, req *LoginByPwdRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	// LoginBySms 短信验证码登录（自动注册）
	LoginBySms(ctx context.Context, req *LoginBySmsRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	// Logout 退出登录
	Logout(ctx context.Context, req *LogoutRequest, opts ...http.CallOption) (rsp *LogoutReply, err error)
	// RefreshToken 刷新 Token
	RefreshToken(ctx context.Context, req *RefreshTokenRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
	// Register 注册（手机号 + 验证码 + 密码）
	Register(ctx context.Context, req *RegisterRequest, opts ...http.CallOption) (rsp *RegisterReply, err error)
	// SendSmsCode 发送短信验证码
	SendSmsCode(ctx context.Context, req *SendSmsRequest, opts ...http.CallOption) (rsp *SendSmsReply, err error)
	// UpdateProfile 部分更新个人信息（邮箱等，从Token解析）
	UpdateProfile(ctx context.Context, req *UpdateProfileRequest, opts ...http.CallOption) (rsp *UpdateProfileReply, err error)
	// UpdateUserById 部分更新指定用户信息（管理员操作他人，需要权限检查）
	UpdateUserById(ctx context.Context, req *UpdateUserByIdRequest, opts ...http.CallOption) (rsp *UpdateUserByIdReply, err error)
	// UpdateUserMe 部分更新当前登录用户信息（普通用户修改自己，从Token解析）
	UpdateUserMe(ctx context.Context, req *UpdateUserMeRequest, opts ...http.CallOption) (rsp *UpdateUserMeReply, err error)
}

type UserServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewUserServiceHTTPClient(client *http.Client) UserServiceHTTPClient {
	return &UserServiceHTTPClientImpl{client}
}

// GetUserById 获取指定用户信息（管理员操作他人，需要权限检查）
func (c *UserServiceHTTPClientImpl) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...http.CallOption) (*GetUserByIdReply, error) {
	var out GetUserByIdReply
	pattern := "/v1/user/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserServiceGetUserById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetUserMe 获取当前登录用户信息（普通用户操作自己，从Token解析）
func (c *UserServiceHTTPClientImpl) GetUserMe(ctx context.Context, in *GetUserMeRequest, opts ...http.CallOption) (*GetUserMeReply, error) {
	var out GetUserMeReply
	pattern := "/v1/user/me"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserServiceGetUserMe))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Login 登录（账号 + 密码）
func (c *UserServiceHTTPClientImpl) Login(ctx context.Context, in *LoginByPwdRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/v1/user/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserServiceLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoginBySms 短信验证码登录（自动注册）
func (c *UserServiceHTTPClientImpl) LoginBySms(ctx context.Context, in *LoginBySmsRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/v1/user/login/sms"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserServiceLoginBySms))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Logout 退出登录
func (c *UserServiceHTTPClientImpl) Logout(ctx context.Context, in *LogoutRequest, opts ...http.CallOption) (*LogoutReply, error) {
	var out LogoutReply
	pattern := "/v1/user/logout"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserServiceLogout))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RefreshToken 刷新 Token
func (c *UserServiceHTTPClientImpl) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/v1/user/token/refresh"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserServiceRefreshToken))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Register 注册（手机号 + 验证码 + 密码）
func (c *UserServiceHTTPClientImpl) Register(ctx context.Context, in *RegisterRequest, opts ...http.CallOption) (*RegisterReply, error) {
	var out RegisterReply
	pattern := "/v1/user/register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserServiceRegister))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SendSmsCode 发送短信验证码
func (c *UserServiceHTTPClientImpl) SendSmsCode(ctx context.Context, in *SendSmsRequest, opts ...http.CallOption) (*SendSmsReply, error) {
	var out SendSmsReply
	pattern := "/v1/user/sms/send"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserServiceSendSmsCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateProfile 部分更新个人信息（邮箱等，从Token解析）
func (c *UserServiceHTTPClientImpl) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...http.CallOption) (*UpdateProfileReply, error) {
	var out UpdateProfileReply
	pattern := "/v1/user/profile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserServiceUpdateProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateUserById 部分更新指定用户信息（管理员操作他人，需要权限检查）
func (c *UserServiceHTTPClientImpl) UpdateUserById(ctx context.Context, in *UpdateUserByIdRequest, opts ...http.CallOption) (*UpdateUserByIdReply, error) {
	var out UpdateUserByIdReply
	pattern := "/v1/user/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserServiceUpdateUserById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateUserMe 部分更新当前登录用户信息（普通用户修改自己，从Token解析）
func (c *UserServiceHTTPClientImpl) UpdateUserMe(ctx context.Context, in *UpdateUserMeRequest, opts ...http.CallOption) (*UpdateUserMeReply, error) {
	var out UpdateUserMeReply
	pattern := "/v1/user/me"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserServiceUpdateUserMe))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
