// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: storage/v1/storage.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCourierServiceApplyCourier = "/api.storage.v1.CourierService/ApplyCourier"
const OperationCourierServiceApproveCourier = "/api.storage.v1.CourierService/ApproveCourier"
const OperationCourierServiceAssignZone = "/api.storage.v1.CourierService/AssignZone"
const OperationCourierServiceCreateZone = "/api.storage.v1.CourierService/CreateZone"
const OperationCourierServiceGetCourierInfo = "/api.storage.v1.CourierService/GetCourierInfo"
const OperationCourierServiceGetCourierList = "/api.storage.v1.CourierService/GetCourierList"
const OperationCourierServiceGetZoneList = "/api.storage.v1.CourierService/GetZoneList"

type CourierServiceHTTPServer interface {
	// ApplyCourier 用户申请成为快递员
	ApplyCourier(context.Context, *ApplyCourierRequest) (*ApplyCourierReply, error)
	// ApproveCourier 管理员审核快递员申请
	ApproveCourier(context.Context, *ApproveCourierRequest) (*ApproveCourierReply, error)
	// AssignZone 管理员分配片区
	AssignZone(context.Context, *AssignZoneRequest) (*AssignZoneReply, error)
	// CreateZone 管理员创建片区
	CreateZone(context.Context, *CreateZoneRequest) (*CreateZoneReply, error)
	// GetCourierInfo 快递员查看自身信息
	GetCourierInfo(context.Context, *GetCourierInfoRequest) (*GetCourierInfoReply, error)
	// GetCourierList 管理员查询快递员列表
	GetCourierList(context.Context, *GetCourierListRequest) (*GetCourierListReply, error)
	// GetZoneList 管理员查询片区列表
	GetZoneList(context.Context, *GetZoneListRequest) (*GetZoneListReply, error)
}

func RegisterCourierServiceHTTPServer(s *http.Server, srv CourierServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/courier/apply", _CourierService_ApplyCourier0_HTTP_Handler(srv))
	r.GET("/v1/courier/info", _CourierService_GetCourierInfo0_HTTP_Handler(srv))
	r.GET("/v1/admin/courier/list", _CourierService_GetCourierList0_HTTP_Handler(srv))
	r.POST("/v1/admin/courier/approve", _CourierService_ApproveCourier0_HTTP_Handler(srv))
	r.POST("/v1/admin/courier/assign-zone", _CourierService_AssignZone0_HTTP_Handler(srv))
	r.POST("/v1/admin/zone/create", _CourierService_CreateZone0_HTTP_Handler(srv))
	r.GET("/v1/admin/zone/list", _CourierService_GetZoneList0_HTTP_Handler(srv))
}

func _CourierService_ApplyCourier0_HTTP_Handler(srv CourierServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApplyCourierRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourierServiceApplyCourier)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApplyCourier(ctx, req.(*ApplyCourierRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplyCourierReply)
		return ctx.Result(200, reply)
	}
}

func _CourierService_GetCourierInfo0_HTTP_Handler(srv CourierServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCourierInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourierServiceGetCourierInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCourierInfo(ctx, req.(*GetCourierInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCourierInfoReply)
		return ctx.Result(200, reply)
	}
}

func _CourierService_GetCourierList0_HTTP_Handler(srv CourierServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCourierListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourierServiceGetCourierList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCourierList(ctx, req.(*GetCourierListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCourierListReply)
		return ctx.Result(200, reply)
	}
}

func _CourierService_ApproveCourier0_HTTP_Handler(srv CourierServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApproveCourierRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourierServiceApproveCourier)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApproveCourier(ctx, req.(*ApproveCourierRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApproveCourierReply)
		return ctx.Result(200, reply)
	}
}

func _CourierService_AssignZone0_HTTP_Handler(srv CourierServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignZoneRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourierServiceAssignZone)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignZone(ctx, req.(*AssignZoneRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AssignZoneReply)
		return ctx.Result(200, reply)
	}
}

func _CourierService_CreateZone0_HTTP_Handler(srv CourierServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateZoneRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourierServiceCreateZone)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateZone(ctx, req.(*CreateZoneRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateZoneReply)
		return ctx.Result(200, reply)
	}
}

func _CourierService_GetZoneList0_HTTP_Handler(srv CourierServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetZoneListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCourierServiceGetZoneList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetZoneList(ctx, req.(*GetZoneListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetZoneListReply)
		return ctx.Result(200, reply)
	}
}

type CourierServiceHTTPClient interface {
	// ApplyCourier 用户申请成为快递员
	ApplyCourier(ctx context.Context, req *ApplyCourierRequest, opts ...http.CallOption) (rsp *ApplyCourierReply, err error)
	// ApproveCourier 管理员审核快递员申请
	ApproveCourier(ctx context.Context, req *ApproveCourierRequest, opts ...http.CallOption) (rsp *ApproveCourierReply, err error)
	// AssignZone 管理员分配片区
	AssignZone(ctx context.Context, req *AssignZoneRequest, opts ...http.CallOption) (rsp *AssignZoneReply, err error)
	// CreateZone 管理员创建片区
	CreateZone(ctx context.Context, req *CreateZoneRequest, opts ...http.CallOption) (rsp *CreateZoneReply, err error)
	// GetCourierInfo 快递员查看自身信息
	GetCourierInfo(ctx context.Context, req *GetCourierInfoRequest, opts ...http.CallOption) (rsp *GetCourierInfoReply, err error)
	// GetCourierList 管理员查询快递员列表
	GetCourierList(ctx context.Context, req *GetCourierListRequest, opts ...http.CallOption) (rsp *GetCourierListReply, err error)
	// GetZoneList 管理员查询片区列表
	GetZoneList(ctx context.Context, req *GetZoneListRequest, opts ...http.CallOption) (rsp *GetZoneListReply, err error)
}

type CourierServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCourierServiceHTTPClient(client *http.Client) CourierServiceHTTPClient {
	return &CourierServiceHTTPClientImpl{client}
}

// ApplyCourier 用户申请成为快递员
func (c *CourierServiceHTTPClientImpl) ApplyCourier(ctx context.Context, in *ApplyCourierRequest, opts ...http.CallOption) (*ApplyCourierReply, error) {
	var out ApplyCourierReply
	pattern := "/v1/courier/apply"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCourierServiceApplyCourier))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ApproveCourier 管理员审核快递员申请
func (c *CourierServiceHTTPClientImpl) ApproveCourier(ctx context.Context, in *ApproveCourierRequest, opts ...http.CallOption) (*ApproveCourierReply, error) {
	var out ApproveCourierReply
	pattern := "/v1/admin/courier/approve"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCourierServiceApproveCourier))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AssignZone 管理员分配片区
func (c *CourierServiceHTTPClientImpl) AssignZone(ctx context.Context, in *AssignZoneRequest, opts ...http.CallOption) (*AssignZoneReply, error) {
	var out AssignZoneReply
	pattern := "/v1/admin/courier/assign-zone"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCourierServiceAssignZone))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateZone 管理员创建片区
func (c *CourierServiceHTTPClientImpl) CreateZone(ctx context.Context, in *CreateZoneRequest, opts ...http.CallOption) (*CreateZoneReply, error) {
	var out CreateZoneReply
	pattern := "/v1/admin/zone/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCourierServiceCreateZone))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCourierInfo 快递员查看自身信息
func (c *CourierServiceHTTPClientImpl) GetCourierInfo(ctx context.Context, in *GetCourierInfoRequest, opts ...http.CallOption) (*GetCourierInfoReply, error) {
	var out GetCourierInfoReply
	pattern := "/v1/courier/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCourierServiceGetCourierInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCourierList 管理员查询快递员列表
func (c *CourierServiceHTTPClientImpl) GetCourierList(ctx context.Context, in *GetCourierListRequest, opts ...http.CallOption) (*GetCourierListReply, error) {
	var out GetCourierListReply
	pattern := "/v1/admin/courier/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCourierServiceGetCourierList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetZoneList 管理员查询片区列表
func (c *CourierServiceHTTPClientImpl) GetZoneList(ctx context.Context, in *GetZoneListRequest, opts ...http.CallOption) (*GetZoneListReply, error) {
	var out GetZoneListReply
	pattern := "/v1/admin/zone/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCourierServiceGetZoneList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationExpressServiceAppendTrace = "/api.storage.v1.ExpressService/AppendTrace"
const OperationExpressServiceCancelExpress = "/api.storage.v1.ExpressService/CancelExpress"
const OperationExpressServiceCancelTimeoutOrder = "/api.storage.v1.ExpressService/CancelTimeoutOrder"
const OperationExpressServiceCheckCoverage = "/api.storage.v1.ExpressService/CheckCoverage"
const OperationExpressServiceCreateExpress = "/api.storage.v1.ExpressService/CreateExpress"
const OperationExpressServiceDeliverToCabinet = "/api.storage.v1.ExpressService/DeliverToCabinet"
const OperationExpressServiceDeliverToStation = "/api.storage.v1.ExpressService/DeliverToStation"
const OperationExpressServiceGetCourierPendingOrders = "/api.storage.v1.ExpressService/GetCourierPendingOrders"
const OperationExpressServiceGetExpress = "/api.storage.v1.ExpressService/GetExpress"
const OperationExpressServiceGetTrace = "/api.storage.v1.ExpressService/GetTrace"
const OperationExpressServiceListExpress = "/api.storage.v1.ExpressService/ListExpress"
const OperationExpressServiceManualAssignOrder = "/api.storage.v1.ExpressService/ManualAssignOrder"
const OperationExpressServicePickupExpress = "/api.storage.v1.ExpressService/PickupExpress"
const OperationExpressServicePickupFromCabinet = "/api.storage.v1.ExpressService/PickupFromCabinet"
const OperationExpressServicePickupFromStation = "/api.storage.v1.ExpressService/PickupFromStation"
const OperationExpressServiceUpdateOrderStatus = "/api.storage.v1.ExpressService/UpdateOrderStatus"
const OperationExpressServiceVerifyPickup = "/api.storage.v1.ExpressService/VerifyPickup"

type ExpressServiceHTTPServer interface {
	// AppendTrace 追加轨迹项（Phase 3 新增）
	AppendTrace(context.Context, *AppendTraceRequest) (*AppendTraceReply, error)
	// CancelExpress 取消订单
	CancelExpress(context.Context, *CancelExpressRequest) (*CancelExpressReply, error)
	// CancelTimeoutOrder 取消超时订单（Phase 2 新增）
	CancelTimeoutOrder(context.Context, *CancelTimeoutOrderRequest) (*CancelTimeoutOrderReply, error)
	// CheckCoverage 区域覆盖检查（Phase 2 新增）
	CheckCoverage(context.Context, *CheckCoverageRequest) (*CheckCoverageReply, error)
	// CreateExpress 创建寄件订单（派单 + 生成取件码）
	CreateExpress(context.Context, *CreateExpressRequest) (*CreateExpressReply, error)
	// DeliverToCabinet 快递柜投递（Phase 3 新增）
	DeliverToCabinet(context.Context, *DeliverToCabinetRequest) (*DeliverToCabinetReply, error)
	// DeliverToStation 驿站投递（Phase 3 新增）
	DeliverToStation(context.Context, *DeliverToStationRequest) (*DeliverToStationReply, error)
	// GetCourierPendingOrders 快递员待揽收列表（Phase 2 新增）
	GetCourierPendingOrders(context.Context, *GetCourierPendingOrdersRequest) (*GetCourierPendingOrdersReply, error)
	// GetExpress 订单详情
	GetExpress(context.Context, *GetExpressRequest) (*GetExpressReply, error)
	// GetTrace 查询物流轨迹（Phase 3 新增）
	GetTrace(context.Context, *GetTraceRequest) (*GetTraceReply, error)
	// ListExpress 我的快递列表（分页）
	ListExpress(context.Context, *ListExpressRequest) (*ListExpressReply, error)
	// ManualAssignOrder 管理员人工派单（Phase 2 新增）
	ManualAssignOrder(context.Context, *ManualAssignOrderRequest) (*ManualAssignOrderReply, error)
	// PickupExpress 确认取件（驿站取件）
	PickupExpress(context.Context, *PickupExpressRequest) (*PickupExpressReply, error)
	// PickupFromCabinet 快递柜取件（Phase 3 新增）
	PickupFromCabinet(context.Context, *PickupFromCabinetRequest) (*PickupFromCabinetReply, error)
	// PickupFromStation 驿站取件（Phase 3 新增）
	PickupFromStation(context.Context, *PickupFromStationRequest) (*PickupFromStationReply, error)
	// UpdateOrderStatus 更新订单状态（Phase 3 新增）
	UpdateOrderStatus(context.Context, *UpdateOrderStatusRequest) (*UpdateOrderStatusReply, error)
	// VerifyPickup 快递员上门核验（Phase 2 新增）
	VerifyPickup(context.Context, *VerifyPickupRequest) (*VerifyPickupReply, error)
}

func RegisterExpressServiceHTTPServer(s *http.Server, srv ExpressServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/express/send", _ExpressService_CreateExpress0_HTTP_Handler(srv))
	r.GET("/v1/express/list", _ExpressService_ListExpress0_HTTP_Handler(srv))
	r.GET("/v1/express/{id}", _ExpressService_GetExpress0_HTTP_Handler(srv))
	r.POST("/v1/express/pickup", _ExpressService_PickupExpress0_HTTP_Handler(srv))
	r.PATCH("/v1/express/{id}/cancel", _ExpressService_CancelExpress0_HTTP_Handler(srv))
	r.POST("/v1/courier/pickup/verify", _ExpressService_VerifyPickup0_HTTP_Handler(srv))
	r.GET("/v1/courier/pending-orders", _ExpressService_GetCourierPendingOrders0_HTTP_Handler(srv))
	r.POST("/v1/order/cancel-timeout", _ExpressService_CancelTimeoutOrder0_HTTP_Handler(srv))
	r.GET("/v1/order/coverage-check", _ExpressService_CheckCoverage0_HTTP_Handler(srv))
	r.POST("/v1/admin/order/manual-assign", _ExpressService_ManualAssignOrder0_HTTP_Handler(srv))
	r.POST("/v1/express/{orderId}/status", _ExpressService_UpdateOrderStatus0_HTTP_Handler(srv))
	r.POST("/v1/express/deliver/station", _ExpressService_DeliverToStation0_HTTP_Handler(srv))
	r.POST("/v1/express/pickup/station", _ExpressService_PickupFromStation0_HTTP_Handler(srv))
	r.POST("/v1/express/deliver/cabinet", _ExpressService_DeliverToCabinet0_HTTP_Handler(srv))
	r.POST("/v1/express/pickup/cabinet", _ExpressService_PickupFromCabinet0_HTTP_Handler(srv))
	r.GET("/v1/express/{orderId}/trace", _ExpressService_GetTrace0_HTTP_Handler(srv))
	r.POST("/v1/express/{orderId}/trace/append", _ExpressService_AppendTrace0_HTTP_Handler(srv))
}

func _ExpressService_CreateExpress0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateExpressRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceCreateExpress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateExpress(ctx, req.(*CreateExpressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateExpressReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_ListExpress0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListExpressRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceListExpress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListExpress(ctx, req.(*ListExpressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListExpressReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_GetExpress0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetExpressRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceGetExpress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetExpress(ctx, req.(*GetExpressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetExpressReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_PickupExpress0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PickupExpressRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServicePickupExpress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PickupExpress(ctx, req.(*PickupExpressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PickupExpressReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_CancelExpress0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelExpressRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceCancelExpress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelExpress(ctx, req.(*CancelExpressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CancelExpressReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_VerifyPickup0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in VerifyPickupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceVerifyPickup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.VerifyPickup(ctx, req.(*VerifyPickupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*VerifyPickupReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_GetCourierPendingOrders0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCourierPendingOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceGetCourierPendingOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCourierPendingOrders(ctx, req.(*GetCourierPendingOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCourierPendingOrdersReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_CancelTimeoutOrder0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelTimeoutOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceCancelTimeoutOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelTimeoutOrder(ctx, req.(*CancelTimeoutOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CancelTimeoutOrderReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_CheckCoverage0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckCoverageRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceCheckCoverage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckCoverage(ctx, req.(*CheckCoverageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckCoverageReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_ManualAssignOrder0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ManualAssignOrderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceManualAssignOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ManualAssignOrder(ctx, req.(*ManualAssignOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ManualAssignOrderReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_UpdateOrderStatus0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateOrderStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceUpdateOrderStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateOrderStatus(ctx, req.(*UpdateOrderStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateOrderStatusReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_DeliverToStation0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeliverToStationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceDeliverToStation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeliverToStation(ctx, req.(*DeliverToStationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeliverToStationReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_PickupFromStation0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PickupFromStationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServicePickupFromStation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PickupFromStation(ctx, req.(*PickupFromStationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PickupFromStationReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_DeliverToCabinet0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeliverToCabinetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceDeliverToCabinet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeliverToCabinet(ctx, req.(*DeliverToCabinetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeliverToCabinetReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_PickupFromCabinet0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PickupFromCabinetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServicePickupFromCabinet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PickupFromCabinet(ctx, req.(*PickupFromCabinetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PickupFromCabinetReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_GetTrace0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTraceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceGetTrace)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTrace(ctx, req.(*GetTraceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTraceReply)
		return ctx.Result(200, reply)
	}
}

func _ExpressService_AppendTrace0_HTTP_Handler(srv ExpressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AppendTraceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationExpressServiceAppendTrace)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AppendTrace(ctx, req.(*AppendTraceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AppendTraceReply)
		return ctx.Result(200, reply)
	}
}

type ExpressServiceHTTPClient interface {
	// AppendTrace 追加轨迹项（Phase 3 新增）
	AppendTrace(ctx context.Context, req *AppendTraceRequest, opts ...http.CallOption) (rsp *AppendTraceReply, err error)
	// CancelExpress 取消订单
	CancelExpress(ctx context.Context, req *CancelExpressRequest, opts ...http.CallOption) (rsp *CancelExpressReply, err error)
	// CancelTimeoutOrder 取消超时订单（Phase 2 新增）
	CancelTimeoutOrder(ctx context.Context, req *CancelTimeoutOrderRequest, opts ...http.CallOption) (rsp *CancelTimeoutOrderReply, err error)
	// CheckCoverage 区域覆盖检查（Phase 2 新增）
	CheckCoverage(ctx context.Context, req *CheckCoverageRequest, opts ...http.CallOption) (rsp *CheckCoverageReply, err error)
	// CreateExpress 创建寄件订单（派单 + 生成取件码）
	CreateExpress(ctx context.Context, req *CreateExpressRequest, opts ...http.CallOption) (rsp *CreateExpressReply, err error)
	// DeliverToCabinet 快递柜投递（Phase 3 新增）
	DeliverToCabinet(ctx context.Context, req *DeliverToCabinetRequest, opts ...http.CallOption) (rsp *DeliverToCabinetReply, err error)
	// DeliverToStation 驿站投递（Phase 3 新增）
	DeliverToStation(ctx context.Context, req *DeliverToStationRequest, opts ...http.CallOption) (rsp *DeliverToStationReply, err error)
	// GetCourierPendingOrders 快递员待揽收列表（Phase 2 新增）
	GetCourierPendingOrders(ctx context.Context, req *GetCourierPendingOrdersRequest, opts ...http.CallOption) (rsp *GetCourierPendingOrdersReply, err error)
	// GetExpress 订单详情
	GetExpress(ctx context.Context, req *GetExpressRequest, opts ...http.CallOption) (rsp *GetExpressReply, err error)
	// GetTrace 查询物流轨迹（Phase 3 新增）
	GetTrace(ctx context.Context, req *GetTraceRequest, opts ...http.CallOption) (rsp *GetTraceReply, err error)
	// ListExpress 我的快递列表（分页）
	ListExpress(ctx context.Context, req *ListExpressRequest, opts ...http.CallOption) (rsp *ListExpressReply, err error)
	// ManualAssignOrder 管理员人工派单（Phase 2 新增）
	ManualAssignOrder(ctx context.Context, req *ManualAssignOrderRequest, opts ...http.CallOption) (rsp *ManualAssignOrderReply, err error)
	// PickupExpress 确认取件（驿站取件）
	PickupExpress(ctx context.Context, req *PickupExpressRequest, opts ...http.CallOption) (rsp *PickupExpressReply, err error)
	// PickupFromCabinet 快递柜取件（Phase 3 新增）
	PickupFromCabinet(ctx context.Context, req *PickupFromCabinetRequest, opts ...http.CallOption) (rsp *PickupFromCabinetReply, err error)
	// PickupFromStation 驿站取件（Phase 3 新增）
	PickupFromStation(ctx context.Context, req *PickupFromStationRequest, opts ...http.CallOption) (rsp *PickupFromStationReply, err error)
	// UpdateOrderStatus 更新订单状态（Phase 3 新增）
	UpdateOrderStatus(ctx context.Context, req *UpdateOrderStatusRequest, opts ...http.CallOption) (rsp *UpdateOrderStatusReply, err error)
	// VerifyPickup 快递员上门核验（Phase 2 新增）
	VerifyPickup(ctx context.Context, req *VerifyPickupRequest, opts ...http.CallOption) (rsp *VerifyPickupReply, err error)
}

type ExpressServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewExpressServiceHTTPClient(client *http.Client) ExpressServiceHTTPClient {
	return &ExpressServiceHTTPClientImpl{client}
}

// AppendTrace 追加轨迹项（Phase 3 新增）
func (c *ExpressServiceHTTPClientImpl) AppendTrace(ctx context.Context, in *AppendTraceRequest, opts ...http.CallOption) (*AppendTraceReply, error) {
	var out AppendTraceReply
	pattern := "/v1/express/{orderId}/trace/append"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExpressServiceAppendTrace))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CancelExpress 取消订单
func (c *ExpressServiceHTTPClientImpl) CancelExpress(ctx context.Context, in *CancelExpressRequest, opts ...http.CallOption) (*CancelExpressReply, error) {
	var out CancelExpressReply
	pattern := "/v1/express/{id}/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExpressServiceCancelExpress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CancelTimeoutOrder 取消超时订单（Phase 2 新增）
func (c *ExpressServiceHTTPClientImpl) CancelTimeoutOrder(ctx context.Context, in *CancelTimeoutOrderRequest, opts ...http.CallOption) (*CancelTimeoutOrderReply, error) {
	var out CancelTimeoutOrderReply
	pattern := "/v1/order/cancel-timeout"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExpressServiceCancelTimeoutOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CheckCoverage 区域覆盖检查（Phase 2 新增）
func (c *ExpressServiceHTTPClientImpl) CheckCoverage(ctx context.Context, in *CheckCoverageRequest, opts ...http.CallOption) (*CheckCoverageReply, error) {
	var out CheckCoverageReply
	pattern := "/v1/order/coverage-check"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationExpressServiceCheckCoverage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateExpress 创建寄件订单（派单 + 生成取件码）
func (c *ExpressServiceHTTPClientImpl) CreateExpress(ctx context.Context, in *CreateExpressRequest, opts ...http.CallOption) (*CreateExpressReply, error) {
	var out CreateExpressReply
	pattern := "/v1/express/send"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExpressServiceCreateExpress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeliverToCabinet 快递柜投递（Phase 3 新增）
func (c *ExpressServiceHTTPClientImpl) DeliverToCabinet(ctx context.Context, in *DeliverToCabinetRequest, opts ...http.CallOption) (*DeliverToCabinetReply, error) {
	var out DeliverToCabinetReply
	pattern := "/v1/express/deliver/cabinet"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExpressServiceDeliverToCabinet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeliverToStation 驿站投递（Phase 3 新增）
func (c *ExpressServiceHTTPClientImpl) DeliverToStation(ctx context.Context, in *DeliverToStationRequest, opts ...http.CallOption) (*DeliverToStationReply, error) {
	var out DeliverToStationReply
	pattern := "/v1/express/deliver/station"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExpressServiceDeliverToStation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCourierPendingOrders 快递员待揽收列表（Phase 2 新增）
func (c *ExpressServiceHTTPClientImpl) GetCourierPendingOrders(ctx context.Context, in *GetCourierPendingOrdersRequest, opts ...http.CallOption) (*GetCourierPendingOrdersReply, error) {
	var out GetCourierPendingOrdersReply
	pattern := "/v1/courier/pending-orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationExpressServiceGetCourierPendingOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetExpress 订单详情
func (c *ExpressServiceHTTPClientImpl) GetExpress(ctx context.Context, in *GetExpressRequest, opts ...http.CallOption) (*GetExpressReply, error) {
	var out GetExpressReply
	pattern := "/v1/express/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationExpressServiceGetExpress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTrace 查询物流轨迹（Phase 3 新增）
func (c *ExpressServiceHTTPClientImpl) GetTrace(ctx context.Context, in *GetTraceRequest, opts ...http.CallOption) (*GetTraceReply, error) {
	var out GetTraceReply
	pattern := "/v1/express/{orderId}/trace"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationExpressServiceGetTrace))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListExpress 我的快递列表（分页）
func (c *ExpressServiceHTTPClientImpl) ListExpress(ctx context.Context, in *ListExpressRequest, opts ...http.CallOption) (*ListExpressReply, error) {
	var out ListExpressReply
	pattern := "/v1/express/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationExpressServiceListExpress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ManualAssignOrder 管理员人工派单（Phase 2 新增）
func (c *ExpressServiceHTTPClientImpl) ManualAssignOrder(ctx context.Context, in *ManualAssignOrderRequest, opts ...http.CallOption) (*ManualAssignOrderReply, error) {
	var out ManualAssignOrderReply
	pattern := "/v1/admin/order/manual-assign"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExpressServiceManualAssignOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PickupExpress 确认取件（驿站取件）
func (c *ExpressServiceHTTPClientImpl) PickupExpress(ctx context.Context, in *PickupExpressRequest, opts ...http.CallOption) (*PickupExpressReply, error) {
	var out PickupExpressReply
	pattern := "/v1/express/pickup"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExpressServicePickupExpress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PickupFromCabinet 快递柜取件（Phase 3 新增）
func (c *ExpressServiceHTTPClientImpl) PickupFromCabinet(ctx context.Context, in *PickupFromCabinetRequest, opts ...http.CallOption) (*PickupFromCabinetReply, error) {
	var out PickupFromCabinetReply
	pattern := "/v1/express/pickup/cabinet"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExpressServicePickupFromCabinet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PickupFromStation 驿站取件（Phase 3 新增）
func (c *ExpressServiceHTTPClientImpl) PickupFromStation(ctx context.Context, in *PickupFromStationRequest, opts ...http.CallOption) (*PickupFromStationReply, error) {
	var out PickupFromStationReply
	pattern := "/v1/express/pickup/station"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExpressServicePickupFromStation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateOrderStatus 更新订单状态（Phase 3 新增）
func (c *ExpressServiceHTTPClientImpl) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...http.CallOption) (*UpdateOrderStatusReply, error) {
	var out UpdateOrderStatusReply
	pattern := "/v1/express/{orderId}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExpressServiceUpdateOrderStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// VerifyPickup 快递员上门核验（Phase 2 新增）
func (c *ExpressServiceHTTPClientImpl) VerifyPickup(ctx context.Context, in *VerifyPickupRequest, opts ...http.CallOption) (*VerifyPickupReply, error) {
	var out VerifyPickupReply
	pattern := "/v1/courier/pickup/verify"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationExpressServiceVerifyPickup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationStationServiceCreateStation = "/api.storage.v1.StationService/CreateStation"
const OperationStationServiceGetStation = "/api.storage.v1.StationService/GetStation"
const OperationStationServiceListStations = "/api.storage.v1.StationService/ListStations"
const OperationStationServiceUpdateStation = "/api.storage.v1.StationService/UpdateStation"

type StationServiceHTTPServer interface {
	// CreateStation 创建驿站（管理员）
	CreateStation(context.Context, *CreateStationRequest) (*CreateStationReply, error)
	// GetStation 驿站详情
	GetStation(context.Context, *GetStationRequest) (*GetStationReply, error)
	// ListStations 驿站列表
	ListStations(context.Context, *ListStationsRequest) (*ListStationsReply, error)
	// UpdateStation 更新驿站（管理员）
	UpdateStation(context.Context, *UpdateStationRequest) (*UpdateStationReply, error)
}

func RegisterStationServiceHTTPServer(s *http.Server, srv StationServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/stations", _StationService_ListStations0_HTTP_Handler(srv))
	r.GET("/v1/stations/{id}", _StationService_GetStation0_HTTP_Handler(srv))
	r.POST("/v1/admin/stations", _StationService_CreateStation0_HTTP_Handler(srv))
	r.PUT("/v1/admin/stations/{id}", _StationService_UpdateStation0_HTTP_Handler(srv))
}

func _StationService_ListStations0_HTTP_Handler(srv StationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListStationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStationServiceListStations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListStations(ctx, req.(*ListStationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListStationsReply)
		return ctx.Result(200, reply)
	}
}

func _StationService_GetStation0_HTTP_Handler(srv StationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetStationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStationServiceGetStation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetStation(ctx, req.(*GetStationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetStationReply)
		return ctx.Result(200, reply)
	}
}

func _StationService_CreateStation0_HTTP_Handler(srv StationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateStationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStationServiceCreateStation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateStation(ctx, req.(*CreateStationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateStationReply)
		return ctx.Result(200, reply)
	}
}

func _StationService_UpdateStation0_HTTP_Handler(srv StationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStationServiceUpdateStation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStation(ctx, req.(*UpdateStationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateStationReply)
		return ctx.Result(200, reply)
	}
}

type StationServiceHTTPClient interface {
	// CreateStation 创建驿站（管理员）
	CreateStation(ctx context.Context, req *CreateStationRequest, opts ...http.CallOption) (rsp *CreateStationReply, err error)
	// GetStation 驿站详情
	GetStation(ctx context.Context, req *GetStationRequest, opts ...http.CallOption) (rsp *GetStationReply, err error)
	// ListStations 驿站列表
	ListStations(ctx context.Context, req *ListStationsRequest, opts ...http.CallOption) (rsp *ListStationsReply, err error)
	// UpdateStation 更新驿站（管理员）
	UpdateStation(ctx context.Context, req *UpdateStationRequest, opts ...http.CallOption) (rsp *UpdateStationReply, err error)
}

type StationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewStationServiceHTTPClient(client *http.Client) StationServiceHTTPClient {
	return &StationServiceHTTPClientImpl{client}
}

// CreateStation 创建驿站（管理员）
func (c *StationServiceHTTPClientImpl) CreateStation(ctx context.Context, in *CreateStationRequest, opts ...http.CallOption) (*CreateStationReply, error) {
	var out CreateStationReply
	pattern := "/v1/admin/stations"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStationServiceCreateStation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStation 驿站详情
func (c *StationServiceHTTPClientImpl) GetStation(ctx context.Context, in *GetStationRequest, opts ...http.CallOption) (*GetStationReply, error) {
	var out GetStationReply
	pattern := "/v1/stations/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStationServiceGetStation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListStations 驿站列表
func (c *StationServiceHTTPClientImpl) ListStations(ctx context.Context, in *ListStationsRequest, opts ...http.CallOption) (*ListStationsReply, error) {
	var out ListStationsReply
	pattern := "/v1/stations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStationServiceListStations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateStation 更新驿站（管理员）
func (c *StationServiceHTTPClientImpl) UpdateStation(ctx context.Context, in *UpdateStationRequest, opts ...http.CallOption) (*UpdateStationReply, error) {
	var out UpdateStationReply
	pattern := "/v1/admin/stations/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStationServiceUpdateStation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationCabinetServiceCreateCabinet = "/api.storage.v1.CabinetService/CreateCabinet"
const OperationCabinetServiceGetAvailableGrids = "/api.storage.v1.CabinetService/GetAvailableGrids"
const OperationCabinetServiceGetCabinet = "/api.storage.v1.CabinetService/GetCabinet"
const OperationCabinetServiceListCabinets = "/api.storage.v1.CabinetService/ListCabinets"
const OperationCabinetServiceListGrids = "/api.storage.v1.CabinetService/ListGrids"
const OperationCabinetServiceReleaseGrid = "/api.storage.v1.CabinetService/ReleaseGrid"
const OperationCabinetServiceUpdateCabinet = "/api.storage.v1.CabinetService/UpdateCabinet"

type CabinetServiceHTTPServer interface {
	// CreateCabinet 创建快递柜（管理员）
	CreateCabinet(context.Context, *CreateCabinetRequest) (*CreateCabinetReply, error)
	// GetAvailableGrids 空闲柜格列表
	GetAvailableGrids(context.Context, *GetAvailableGridsRequest) (*GetAvailableGridsReply, error)
	// GetCabinet 快递柜详情
	GetCabinet(context.Context, *GetCabinetRequest) (*GetCabinetReply, error)
	// ListCabinets 快递柜列表
	ListCabinets(context.Context, *ListCabinetsRequest) (*ListCabinetsReply, error)
	// ListGrids 柜格列表（指定快递柜）
	ListGrids(context.Context, *ListGridsRequest) (*ListGridsReply, error)
	// ReleaseGrid 释放柜格（管理员/运维）
	ReleaseGrid(context.Context, *ReleaseGridRequest) (*ReleaseGridReply, error)
	// UpdateCabinet 更新快递柜（管理员）
	UpdateCabinet(context.Context, *UpdateCabinetRequest) (*UpdateCabinetReply, error)
}

func RegisterCabinetServiceHTTPServer(s *http.Server, srv CabinetServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/cabinets", _CabinetService_ListCabinets0_HTTP_Handler(srv))
	r.GET("/v1/cabinets/{id}", _CabinetService_GetCabinet0_HTTP_Handler(srv))
	r.POST("/v1/admin/cabinets", _CabinetService_CreateCabinet0_HTTP_Handler(srv))
	r.PUT("/v1/admin/cabinets/{id}", _CabinetService_UpdateCabinet0_HTTP_Handler(srv))
	r.GET("/v1/cabinets/{cabinetId}/grids", _CabinetService_ListGrids0_HTTP_Handler(srv))
	r.GET("/v1/cabinets/{cabinetId}/grids/available", _CabinetService_GetAvailableGrids0_HTTP_Handler(srv))
	r.POST("/v1/admin/grids/{gridId}/release", _CabinetService_ReleaseGrid0_HTTP_Handler(srv))
}

func _CabinetService_ListCabinets0_HTTP_Handler(srv CabinetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCabinetsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCabinetServiceListCabinets)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCabinets(ctx, req.(*ListCabinetsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCabinetsReply)
		return ctx.Result(200, reply)
	}
}

func _CabinetService_GetCabinet0_HTTP_Handler(srv CabinetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCabinetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCabinetServiceGetCabinet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCabinet(ctx, req.(*GetCabinetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCabinetReply)
		return ctx.Result(200, reply)
	}
}

func _CabinetService_CreateCabinet0_HTTP_Handler(srv CabinetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCabinetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCabinetServiceCreateCabinet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCabinet(ctx, req.(*CreateCabinetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateCabinetReply)
		return ctx.Result(200, reply)
	}
}

func _CabinetService_UpdateCabinet0_HTTP_Handler(srv CabinetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCabinetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCabinetServiceUpdateCabinet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCabinet(ctx, req.(*UpdateCabinetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCabinetReply)
		return ctx.Result(200, reply)
	}
}

func _CabinetService_ListGrids0_HTTP_Handler(srv CabinetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGridsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCabinetServiceListGrids)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGrids(ctx, req.(*ListGridsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGridsReply)
		return ctx.Result(200, reply)
	}
}

func _CabinetService_GetAvailableGrids0_HTTP_Handler(srv CabinetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAvailableGridsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCabinetServiceGetAvailableGrids)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAvailableGrids(ctx, req.(*GetAvailableGridsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAvailableGridsReply)
		return ctx.Result(200, reply)
	}
}

func _CabinetService_ReleaseGrid0_HTTP_Handler(srv CabinetServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReleaseGridRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCabinetServiceReleaseGrid)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReleaseGrid(ctx, req.(*ReleaseGridRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReleaseGridReply)
		return ctx.Result(200, reply)
	}
}

type CabinetServiceHTTPClient interface {
	// CreateCabinet 创建快递柜（管理员）
	CreateCabinet(ctx context.Context, req *CreateCabinetRequest, opts ...http.CallOption) (rsp *CreateCabinetReply, err error)
	// GetAvailableGrids 空闲柜格列表
	GetAvailableGrids(ctx context.Context, req *GetAvailableGridsRequest, opts ...http.CallOption) (rsp *GetAvailableGridsReply, err error)
	// GetCabinet 快递柜详情
	GetCabinet(ctx context.Context, req *GetCabinetRequest, opts ...http.CallOption) (rsp *GetCabinetReply, err error)
	// ListCabinets 快递柜列表
	ListCabinets(ctx context.Context, req *ListCabinetsRequest, opts ...http.CallOption) (rsp *ListCabinetsReply, err error)
	// ListGrids 柜格列表（指定快递柜）
	ListGrids(ctx context.Context, req *ListGridsRequest, opts ...http.CallOption) (rsp *ListGridsReply, err error)
	// ReleaseGrid 释放柜格（管理员/运维）
	ReleaseGrid(ctx context.Context, req *ReleaseGridRequest, opts ...http.CallOption) (rsp *ReleaseGridReply, err error)
	// UpdateCabinet 更新快递柜（管理员）
	UpdateCabinet(ctx context.Context, req *UpdateCabinetRequest, opts ...http.CallOption) (rsp *UpdateCabinetReply, err error)
}

type CabinetServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCabinetServiceHTTPClient(client *http.Client) CabinetServiceHTTPClient {
	return &CabinetServiceHTTPClientImpl{client}
}

// CreateCabinet 创建快递柜（管理员）
func (c *CabinetServiceHTTPClientImpl) CreateCabinet(ctx context.Context, in *CreateCabinetRequest, opts ...http.CallOption) (*CreateCabinetReply, error) {
	var out CreateCabinetReply
	pattern := "/v1/admin/cabinets"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCabinetServiceCreateCabinet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAvailableGrids 空闲柜格列表
func (c *CabinetServiceHTTPClientImpl) GetAvailableGrids(ctx context.Context, in *GetAvailableGridsRequest, opts ...http.CallOption) (*GetAvailableGridsReply, error) {
	var out GetAvailableGridsReply
	pattern := "/v1/cabinets/{cabinetId}/grids/available"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCabinetServiceGetAvailableGrids))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCabinet 快递柜详情
func (c *CabinetServiceHTTPClientImpl) GetCabinet(ctx context.Context, in *GetCabinetRequest, opts ...http.CallOption) (*GetCabinetReply, error) {
	var out GetCabinetReply
	pattern := "/v1/cabinets/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCabinetServiceGetCabinet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCabinets 快递柜列表
func (c *CabinetServiceHTTPClientImpl) ListCabinets(ctx context.Context, in *ListCabinetsRequest, opts ...http.CallOption) (*ListCabinetsReply, error) {
	var out ListCabinetsReply
	pattern := "/v1/cabinets"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCabinetServiceListCabinets))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListGrids 柜格列表（指定快递柜）
func (c *CabinetServiceHTTPClientImpl) ListGrids(ctx context.Context, in *ListGridsRequest, opts ...http.CallOption) (*ListGridsReply, error) {
	var out ListGridsReply
	pattern := "/v1/cabinets/{cabinetId}/grids"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCabinetServiceListGrids))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReleaseGrid 释放柜格（管理员/运维）
func (c *CabinetServiceHTTPClientImpl) ReleaseGrid(ctx context.Context, in *ReleaseGridRequest, opts ...http.CallOption) (*ReleaseGridReply, error) {
	var out ReleaseGridReply
	pattern := "/v1/admin/grids/{gridId}/release"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCabinetServiceReleaseGrid))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCabinet 更新快递柜（管理员）
func (c *CabinetServiceHTTPClientImpl) UpdateCabinet(ctx context.Context, in *UpdateCabinetRequest, opts ...http.CallOption) (*UpdateCabinetReply, error) {
	var out UpdateCabinetReply
	pattern := "/v1/admin/cabinets/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCabinetServiceUpdateCabinet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
