// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: storage/v1/storage_callback.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageCallbackService_ReportDoorEvent_FullMethodName = "/api.storage.v1.StorageCallbackService/ReportDoorEvent"
)

// StorageCallbackServiceClient is the client API for StorageCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageCallbackServiceClient interface {
	ReportDoorEvent(ctx context.Context, in *ReportDoorEventRequest, opts ...grpc.CallOption) (*ReportDoorEventReply, error)
}

type storageCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageCallbackServiceClient(cc grpc.ClientConnInterface) StorageCallbackServiceClient {
	return &storageCallbackServiceClient{cc}
}

func (c *storageCallbackServiceClient) ReportDoorEvent(ctx context.Context, in *ReportDoorEventRequest, opts ...grpc.CallOption) (*ReportDoorEventReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportDoorEventReply)
	err := c.cc.Invoke(ctx, StorageCallbackService_ReportDoorEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageCallbackServiceServer is the server API for StorageCallbackService service.
// All implementations must embed UnimplementedStorageCallbackServiceServer
// for forward compatibility.
type StorageCallbackServiceServer interface {
	ReportDoorEvent(context.Context, *ReportDoorEventRequest) (*ReportDoorEventReply, error)
	mustEmbedUnimplementedStorageCallbackServiceServer()
}

// UnimplementedStorageCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageCallbackServiceServer struct{}

func (UnimplementedStorageCallbackServiceServer) ReportDoorEvent(context.Context, *ReportDoorEventRequest) (*ReportDoorEventReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDoorEvent not implemented")
}
func (UnimplementedStorageCallbackServiceServer) mustEmbedUnimplementedStorageCallbackServiceServer() {
}
func (UnimplementedStorageCallbackServiceServer) testEmbeddedByValue() {}

// UnsafeStorageCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageCallbackServiceServer will
// result in compilation errors.
type UnsafeStorageCallbackServiceServer interface {
	mustEmbedUnimplementedStorageCallbackServiceServer()
}

func RegisterStorageCallbackServiceServer(s grpc.ServiceRegistrar, srv StorageCallbackServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageCallbackService_ServiceDesc, srv)
}

func _StorageCallbackService_ReportDoorEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportDoorEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageCallbackServiceServer).ReportDoorEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageCallbackService_ReportDoorEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageCallbackServiceServer).ReportDoorEvent(ctx, req.(*ReportDoorEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageCallbackService_ServiceDesc is the grpc.ServiceDesc for StorageCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.storage.v1.StorageCallbackService",
	HandlerType: (*StorageCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportDoorEvent",
			Handler:    _StorageCallbackService_ReportDoorEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/v1/storage_callback.proto",
}
