// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: storage/v1/storage.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitiateDeliveryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CabinetId       int64                  `protobuf:"varint,1,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`
	CellType        int32                  `protobuf:"varint,2,opt,name=cell_type,json=cellType,proto3" json:"cell_type,omitempty"`
	TrackingNo      string                 `protobuf:"bytes,3,opt,name=tracking_no,json=trackingNo,proto3" json:"tracking_no,omitempty"`
	RecipientUserId int64                  `protobuf:"varint,4,opt,name=recipient_user_id,json=recipientUserId,proto3" json:"recipient_user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitiateDeliveryRequest) Reset() {
	*x = InitiateDeliveryRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateDeliveryRequest) ProtoMessage() {}

func (x *InitiateDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateDeliveryRequest.ProtoReflect.Descriptor instead.
func (*InitiateDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateDeliveryRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *InitiateDeliveryRequest) GetCellType() int32 {
	if x != nil {
		return x.CellType
	}
	return 0
}

func (x *InitiateDeliveryRequest) GetTrackingNo() string {
	if x != nil {
		return x.TrackingNo
	}
	return ""
}

func (x *InitiateDeliveryRequest) GetRecipientUserId() int64 {
	if x != nil {
		return x.RecipientUserId
	}
	return 0
}

type InitiateDeliveryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	CellId        int64                  `protobuf:"varint,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,3,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateDeliveryReply) Reset() {
	*x = InitiateDeliveryReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateDeliveryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateDeliveryReply) ProtoMessage() {}

func (x *InitiateDeliveryReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateDeliveryReply.ProtoReflect.Descriptor instead.
func (*InitiateDeliveryReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateDeliveryReply) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *InitiateDeliveryReply) GetCellId() int64 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *InitiateDeliveryReply) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

type PickupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PickupCode    string                 `protobuf:"bytes,1,opt,name=pickup_code,json=pickupCode,proto3" json:"pickup_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupRequest) Reset() {
	*x = PickupRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupRequest) ProtoMessage() {}

func (x *PickupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupRequest.ProtoReflect.Descriptor instead.
func (*PickupRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *PickupRequest) GetPickupCode() string {
	if x != nil {
		return x.PickupCode
	}
	return ""
}

type PickupReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Fee           int32                  `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CabinetName   string                 `protobuf:"bytes,4,opt,name=cabinet_name,json=cabinetName,proto3" json:"cabinet_name,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,5,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PickupReply) Reset() {
	*x = PickupReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PickupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PickupReply) ProtoMessage() {}

func (x *PickupReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PickupReply.ProtoReflect.Descriptor instead.
func (*PickupReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *PickupReply) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PickupReply) GetFee() int32 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *PickupReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PickupReply) GetCabinetName() string {
	if x != nil {
		return x.CabinetName
	}
	return ""
}

func (x *PickupReply) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

type ConfirmPickupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PickupCode    string                 `protobuf:"bytes,2,opt,name=pickup_code,json=pickupCode,proto3" json:"pickup_code,omitempty"`
	PaidAmount    int32                  `protobuf:"varint,3,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPickupRequest) Reset() {
	*x = ConfirmPickupRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPickupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPickupRequest) ProtoMessage() {}

func (x *ConfirmPickupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPickupRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPickupRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmPickupRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ConfirmPickupRequest) GetPickupCode() string {
	if x != nil {
		return x.PickupCode
	}
	return ""
}

func (x *ConfirmPickupRequest) GetPaidAmount() int32 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

type ConfirmPickupReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPickupReply) Reset() {
	*x = ConfirmPickupReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPickupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPickupReply) ProtoMessage() {}

func (x *ConfirmPickupReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPickupReply.ProtoReflect.Descriptor instead.
func (*ConfirmPickupReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmPickupReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type InitiateShipmentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CabinetId      int64                  `protobuf:"varint,1,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`
	CellType       int32                  `protobuf:"varint,2,opt,name=cell_type,json=cellType,proto3" json:"cell_type,omitempty"`
	CourierCompany string                 `protobuf:"bytes,3,opt,name=courier_company,json=courierCompany,proto3" json:"courier_company,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitiateShipmentRequest) Reset() {
	*x = InitiateShipmentRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateShipmentRequest) ProtoMessage() {}

func (x *InitiateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateShipmentRequest.ProtoReflect.Descriptor instead.
func (*InitiateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{6}
}

func (x *InitiateShipmentRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *InitiateShipmentRequest) GetCellType() int32 {
	if x != nil {
		return x.CellType
	}
	return 0
}

func (x *InitiateShipmentRequest) GetCourierCompany() string {
	if x != nil {
		return x.CourierCompany
	}
	return ""
}

type InitiateShipmentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	CellId        int64                  `protobuf:"varint,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,3,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateShipmentReply) Reset() {
	*x = InitiateShipmentReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateShipmentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateShipmentReply) ProtoMessage() {}

func (x *InitiateShipmentReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateShipmentReply.ProtoReflect.Descriptor instead.
func (*InitiateShipmentReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{7}
}

func (x *InitiateShipmentReply) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *InitiateShipmentReply) GetCellId() int64 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *InitiateShipmentReply) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

type InitiateStorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CabinetId     int64                  `protobuf:"varint,1,opt,name=cabinet_id,json=cabinetId,proto3" json:"cabinet_id,omitempty"`
	CellType      int32                  `protobuf:"varint,2,opt,name=cell_type,json=cellType,proto3" json:"cell_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateStorageRequest) Reset() {
	*x = InitiateStorageRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateStorageRequest) ProtoMessage() {}

func (x *InitiateStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateStorageRequest.ProtoReflect.Descriptor instead.
func (*InitiateStorageRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{8}
}

func (x *InitiateStorageRequest) GetCabinetId() int64 {
	if x != nil {
		return x.CabinetId
	}
	return 0
}

func (x *InitiateStorageRequest) GetCellType() int32 {
	if x != nil {
		return x.CellType
	}
	return 0
}

type InitiateStorageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	CellId        int64                  `protobuf:"varint,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,3,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateStorageReply) Reset() {
	*x = InitiateStorageReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateStorageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateStorageReply) ProtoMessage() {}

func (x *InitiateStorageReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateStorageReply.ProtoReflect.Descriptor instead.
func (*InitiateStorageReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{9}
}

func (x *InitiateStorageReply) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *InitiateStorageReply) GetCellId() int64 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *InitiateStorageReply) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

type RetrieveStorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveStorageRequest) Reset() {
	*x = RetrieveStorageRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveStorageRequest) ProtoMessage() {}

func (x *RetrieveStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveStorageRequest.ProtoReflect.Descriptor instead.
func (*RetrieveStorageRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{10}
}

func (x *RetrieveStorageRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type RetrieveStorageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fee           int32                  `protobuf:"varint,1,opt,name=fee,proto3" json:"fee,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveStorageReply) Reset() {
	*x = RetrieveStorageReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveStorageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveStorageReply) ProtoMessage() {}

func (x *RetrieveStorageReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveStorageReply.ProtoReflect.Descriptor instead.
func (*RetrieveStorageReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{11}
}

func (x *RetrieveStorageReply) GetFee() int32 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *RetrieveStorageReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ConfirmRetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PaidAmount    int32                  `protobuf:"varint,2,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRetrieveRequest) Reset() {
	*x = ConfirmRetrieveRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRetrieveRequest) ProtoMessage() {}

func (x *ConfirmRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRetrieveRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmRetrieveRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ConfirmRetrieveRequest) GetPaidAmount() int32 {
	if x != nil {
		return x.PaidAmount
	}
	return 0
}

type ConfirmRetrieveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRetrieveReply) Reset() {
	*x = ConfirmRetrieveReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRetrieveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRetrieveReply) ProtoMessage() {}

func (x *ConfirmRetrieveReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRetrieveReply.ProtoReflect.Descriptor instead.
func (*ConfirmRetrieveReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{13}
}

func (x *ConfirmRetrieveReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type TempOpenCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TempOpenCellRequest) Reset() {
	*x = TempOpenCellRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempOpenCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempOpenCellRequest) ProtoMessage() {}

func (x *TempOpenCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempOpenCellRequest.ProtoReflect.Descriptor instead.
func (*TempOpenCellRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{14}
}

func (x *TempOpenCellRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type TempOpenCellReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TempOpenCellReply) Reset() {
	*x = TempOpenCellReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempOpenCellReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempOpenCellReply) ProtoMessage() {}

func (x *TempOpenCellReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempOpenCellReply.ProtoReflect.Descriptor instead.
func (*TempOpenCellReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{15}
}

func (x *TempOpenCellReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{16}
}

func (x *GetOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	OrderType     string                 `protobuf:"bytes,3,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,5,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	PickupCode    string                 `protobuf:"bytes,6,opt,name=pickup_code,json=pickupCode,proto3" json:"pickup_code,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,7,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DepositedAt   string                 `protobuf:"bytes,9,opt,name=deposited_at,json=depositedAt,proto3" json:"deposited_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReply) Reset() {
	*x = GetOrderReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReply) ProtoMessage() {}

func (x *GetOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReply.ProtoReflect.Descriptor instead.
func (*GetOrderReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{17}
}

func (x *GetOrderReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderReply) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetOrderReply) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *GetOrderReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetOrderReply) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *GetOrderReply) GetPickupCode() string {
	if x != nil {
		return x.PickupCode
	}
	return ""
}

func (x *GetOrderReply) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetOrderReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetOrderReply) GetDepositedAt() string {
	if x != nil {
		return x.DepositedAt
	}
	return ""
}

type ListMyOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderType     string                 `protobuf:"bytes,3,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrdersRequest) Reset() {
	*x = ListMyOrdersRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrdersRequest) ProtoMessage() {}

func (x *ListMyOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListMyOrdersRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{18}
}

func (x *ListMyOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMyOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListMyOrdersRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	OrderType     string                 `protobuf:"bytes,2,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	CabinetName   string                 `protobuf:"bytes,4,opt,name=cabinet_name,json=cabinetName,proto3" json:"cabinet_name,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,5,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_storage_v1_storage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{19}
}

func (x *OrderItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderItem) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

func (x *OrderItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OrderItem) GetCabinetName() string {
	if x != nil {
		return x.CabinetName
	}
	return ""
}

func (x *OrderItem) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *OrderItem) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListMyOrdersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OrderItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrdersReply) Reset() {
	*x = ListMyOrdersReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrdersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrdersReply) ProtoMessage() {}

func (x *ListMyOrdersReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrdersReply.ProtoReflect.Descriptor instead.
func (*ListMyOrdersReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{20}
}

func (x *ListMyOrdersReply) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListMyOrdersReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListCabinetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCabinetsRequest) Reset() {
	*x = ListCabinetsRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCabinetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCabinetsRequest) ProtoMessage() {}

func (x *ListCabinetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCabinetsRequest.ProtoReflect.Descriptor instead.
func (*ListCabinetsRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{21}
}

func (x *ListCabinetsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCabinetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCabinetsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CabinetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LocationName  string                 `protobuf:"bytes,3,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	TotalCells    int32                  `protobuf:"varint,4,opt,name=total_cells,json=totalCells,proto3" json:"total_cells,omitempty"`
	FreeCells     int32                  `protobuf:"varint,5,opt,name=free_cells,json=freeCells,proto3" json:"free_cells,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CabinetItem) Reset() {
	*x = CabinetItem{}
	mi := &file_storage_v1_storage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CabinetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CabinetItem) ProtoMessage() {}

func (x *CabinetItem) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CabinetItem.ProtoReflect.Descriptor instead.
func (*CabinetItem) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{22}
}

func (x *CabinetItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CabinetItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CabinetItem) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *CabinetItem) GetTotalCells() int32 {
	if x != nil {
		return x.TotalCells
	}
	return 0
}

func (x *CabinetItem) GetFreeCells() int32 {
	if x != nil {
		return x.FreeCells
	}
	return 0
}

func (x *CabinetItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListCabinetsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CabinetItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCabinetsReply) Reset() {
	*x = ListCabinetsReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCabinetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCabinetsReply) ProtoMessage() {}

func (x *ListCabinetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCabinetsReply.ProtoReflect.Descriptor instead.
func (*ListCabinetsReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{23}
}

func (x *ListCabinetsReply) GetItems() []*CabinetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCabinetsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetCabinetDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCabinetDetailRequest) Reset() {
	*x = GetCabinetDetailRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCabinetDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCabinetDetailRequest) ProtoMessage() {}

func (x *GetCabinetDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCabinetDetailRequest.ProtoReflect.Descriptor instead.
func (*GetCabinetDetailRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{24}
}

func (x *GetCabinetDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCabinetDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeviceSn      string                 `protobuf:"bytes,3,opt,name=device_sn,json=deviceSn,proto3" json:"device_sn,omitempty"`
	LocationName  string                 `protobuf:"bytes,4,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	TotalCells    int32                  `protobuf:"varint,5,opt,name=total_cells,json=totalCells,proto3" json:"total_cells,omitempty"`
	FreeCells     int32                  `protobuf:"varint,6,opt,name=free_cells,json=freeCells,proto3" json:"free_cells,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Cells         []*CellDetail          `protobuf:"bytes,8,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCabinetDetailReply) Reset() {
	*x = GetCabinetDetailReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCabinetDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCabinetDetailReply) ProtoMessage() {}

func (x *GetCabinetDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCabinetDetailReply.ProtoReflect.Descriptor instead.
func (*GetCabinetDetailReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{25}
}

func (x *GetCabinetDetailReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCabinetDetailReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCabinetDetailReply) GetDeviceSn() string {
	if x != nil {
		return x.DeviceSn
	}
	return ""
}

func (x *GetCabinetDetailReply) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *GetCabinetDetailReply) GetTotalCells() int32 {
	if x != nil {
		return x.TotalCells
	}
	return 0
}

func (x *GetCabinetDetailReply) GetFreeCells() int32 {
	if x != nil {
		return x.FreeCells
	}
	return 0
}

func (x *GetCabinetDetailReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetCabinetDetailReply) GetCells() []*CellDetail {
	if x != nil {
		return x.Cells
	}
	return nil
}

type CellDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,2,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	CellType      int32                  `protobuf:"varint,3,opt,name=cell_type,json=cellType,proto3" json:"cell_type,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellDetail) Reset() {
	*x = CellDetail{}
	mi := &file_storage_v1_storage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellDetail) ProtoMessage() {}

func (x *CellDetail) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellDetail.ProtoReflect.Descriptor instead.
func (*CellDetail) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{26}
}

func (x *CellDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CellDetail) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *CellDetail) GetCellType() int32 {
	if x != nil {
		return x.CellType
	}
	return 0
}

func (x *CellDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ForceOpenCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        int64                  `protobuf:"varint,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceOpenCellRequest) Reset() {
	*x = ForceOpenCellRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceOpenCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceOpenCellRequest) ProtoMessage() {}

func (x *ForceOpenCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceOpenCellRequest.ProtoReflect.Descriptor instead.
func (*ForceOpenCellRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{27}
}

func (x *ForceOpenCellRequest) GetCellId() int64 {
	if x != nil {
		return x.CellId
	}
	return 0
}

func (x *ForceOpenCellRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ForceOpenCellReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceOpenCellReply) Reset() {
	*x = ForceOpenCellReply{}
	mi := &file_storage_v1_storage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceOpenCellReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceOpenCellReply) ProtoMessage() {}

func (x *ForceOpenCellReply) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceOpenCellReply.ProtoReflect.Descriptor instead.
func (*ForceOpenCellReply) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{28}
}

func (x *ForceOpenCellReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_storage_v1_storage_proto protoreflect.FileDescriptor

const file_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x18storage/v1/storage.proto\x12\x0eapi.storage.v1\x1a\x1cgoogle/api/annotations.proto\"\xa2\x01\n" +
	"\x17InitiateDeliveryRequest\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x01 \x01(\x03R\tcabinetId\x12\x1b\n" +
	"\tcell_type\x18\x02 \x01(\x05R\bcellType\x12\x1f\n" +
	"\vtracking_no\x18\x03 \x01(\tR\n" +
	"trackingNo\x12*\n" +
	"\x11recipient_user_id\x18\x04 \x01(\x03R\x0frecipientUserId\"j\n" +
	"\x15InitiateDeliveryReply\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\x03R\x06cellId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x03 \x01(\x05R\tslotIndex\"0\n" +
	"\rPickupRequest\x12\x1f\n" +
	"\vpickup_code\x18\x01 \x01(\tR\n" +
	"pickupCode\"\x94\x01\n" +
	"\vPickupReply\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x10\n" +
	"\x03fee\x18\x02 \x01(\x05R\x03fee\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fcabinet_name\x18\x04 \x01(\tR\vcabinetName\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x05 \x01(\x05R\tslotIndex\"s\n" +
	"\x14ConfirmPickupRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vpickup_code\x18\x02 \x01(\tR\n" +
	"pickupCode\x12\x1f\n" +
	"\vpaid_amount\x18\x03 \x01(\x05R\n" +
	"paidAmount\"$\n" +
	"\x12ConfirmPickupReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"~\n" +
	"\x17InitiateShipmentRequest\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x01 \x01(\x03R\tcabinetId\x12\x1b\n" +
	"\tcell_type\x18\x02 \x01(\x05R\bcellType\x12'\n" +
	"\x0fcourier_company\x18\x03 \x01(\tR\x0ecourierCompany\"j\n" +
	"\x15InitiateShipmentReply\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\x03R\x06cellId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x03 \x01(\x05R\tslotIndex\"T\n" +
	"\x16InitiateStorageRequest\x12\x1d\n" +
	"\n" +
	"cabinet_id\x18\x01 \x01(\x03R\tcabinetId\x12\x1b\n" +
	"\tcell_type\x18\x02 \x01(\x05R\bcellType\"i\n" +
	"\x14InitiateStorageReply\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\x03R\x06cellId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x03 \x01(\x05R\tslotIndex\"3\n" +
	"\x16RetrieveStorageRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"@\n" +
	"\x14RetrieveStorageReply\x12\x10\n" +
	"\x03fee\x18\x01 \x01(\x05R\x03fee\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"T\n" +
	"\x16ConfirmRetrieveRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vpaid_amount\x18\x02 \x01(\x05R\n" +
	"paidAmount\"&\n" +
	"\x14ConfirmRetrieveReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"0\n" +
	"\x13TempOpenCellRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"#\n" +
	"\x11TempOpenCellReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"\x96\x02\n" +
	"\rGetOrderReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"order_type\x18\x03 \x01(\tR\torderType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x05 \x01(\x05R\tslotIndex\x12\x1f\n" +
	"\vpickup_code\x18\x06 \x01(\tR\n" +
	"pickupCode\x12!\n" +
	"\ftotal_amount\x18\a \x01(\x05R\vtotalAmount\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12!\n" +
	"\fdeposited_at\x18\t \x01(\tR\vdepositedAt\"e\n" +
	"\x13ListMyOrdersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"order_type\x18\x03 \x01(\tR\torderType\"\xe1\x01\n" +
	"\tOrderItem\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"order_type\x18\x02 \x01(\tR\torderType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12!\n" +
	"\fcabinet_name\x18\x04 \x01(\tR\vcabinetName\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x05 \x01(\x05R\tslotIndex\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\x05R\vtotalAmount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"Z\n" +
	"\x11ListMyOrdersReply\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.api.storage.v1.OrderItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"^\n" +
	"\x13ListCabinetsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\xae\x01\n" +
	"\vCabinetItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rlocation_name\x18\x03 \x01(\tR\flocationName\x12\x1f\n" +
	"\vtotal_cells\x18\x04 \x01(\x05R\n" +
	"totalCells\x12\x1d\n" +
	"\n" +
	"free_cells\x18\x05 \x01(\x05R\tfreeCells\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"\\\n" +
	"\x11ListCabinetsReply\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.api.storage.v1.CabinetItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\")\n" +
	"\x17GetCabinetDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x87\x02\n" +
	"\x15GetCabinetDetailReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tdevice_sn\x18\x03 \x01(\tR\bdeviceSn\x12#\n" +
	"\rlocation_name\x18\x04 \x01(\tR\flocationName\x12\x1f\n" +
	"\vtotal_cells\x18\x05 \x01(\x05R\n" +
	"totalCells\x12\x1d\n" +
	"\n" +
	"free_cells\x18\x06 \x01(\x05R\tfreeCells\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x120\n" +
	"\x05cells\x18\b \x03(\v2\x1a.api.storage.v1.CellDetailR\x05cells\"p\n" +
	"\n" +
	"CellDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x02 \x01(\x05R\tslotIndex\x12\x1b\n" +
	"\tcell_type\x18\x03 \x01(\x05R\bcellType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"G\n" +
	"\x14ForceOpenCellRequest\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\x03R\x06cellId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"$\n" +
	"\x12ForceOpenCellReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xa8\r\n" +
	"\x0eStorageService\x12\x8c\x01\n" +
	"\x10InitiateDelivery\x12'.api.storage.v1.InitiateDeliveryRequest\x1a%.api.storage.v1.InitiateDeliveryReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/storage/delivery/initiate\x12c\n" +
	"\x06Pickup\x12\x1d.api.storage.v1.PickupRequest\x1a\x1b.api.storage.v1.PickupReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/storage/pickup\x12\x80\x01\n" +
	"\rConfirmPickup\x12$.api.storage.v1.ConfirmPickupRequest\x1a\".api.storage.v1.ConfirmPickupReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/storage/pickup/confirm\x12\x8c\x01\n" +
	"\x10InitiateShipment\x12'.api.storage.v1.InitiateShipmentRequest\x1a%.api.storage.v1.InitiateShipmentReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/storage/shipment/initiate\x12\x86\x01\n" +
	"\x0fInitiateStorage\x12&.api.storage.v1.InitiateStorageRequest\x1a$.api.storage.v1.InitiateStorageReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/storage/store/initiate\x12\x86\x01\n" +
	"\x0fRetrieveStorage\x12&.api.storage.v1.RetrieveStorageRequest\x1a$.api.storage.v1.RetrieveStorageReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/storage/store/retrieve\x12\x8e\x01\n" +
	"\x0fConfirmRetrieve\x12&.api.storage.v1.ConfirmRetrieveRequest\x1a$.api.storage.v1.ConfirmRetrieveReply\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/storage/store/retrieve/confirm\x12~\n" +
	"\fTempOpenCell\x12#.api.storage.v1.TempOpenCellRequest\x1a!.api.storage.v1.TempOpenCellReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/storage/store/temp-open\x12p\n" +
	"\bGetOrder\x12\x1f.api.storage.v1.GetOrderRequest\x1a\x1d.api.storage.v1.GetOrderReply\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/storage/order/{order_no}\x12r\n" +
	"\fListMyOrders\x12#.api.storage.v1.ListMyOrdersRequest\x1a!.api.storage.v1.ListMyOrdersReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/storage/orders\x12t\n" +
	"\fListCabinets\x12#.api.storage.v1.ListCabinetsRequest\x1a!.api.storage.v1.ListCabinetsReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/storage/cabinets\x12\x84\x01\n" +
	"\x10GetCabinetDetail\x12'.api.storage.v1.GetCabinetDetailRequest\x1a%.api.storage.v1.GetCabinetDetailReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/storage/cabinet/{id}\x12\x89\x01\n" +
	"\rForceOpenCell\x12$.api.storage.v1.ForceOpenCellRequest\x1a\".api.storage.v1.ForceOpenCellReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/storage/cabinet/cell/force-openB&Z$shared-device-saas/api/storage/v1;v1b\x06proto3"

var (
	file_storage_v1_storage_proto_rawDescOnce sync.Once
	file_storage_v1_storage_proto_rawDescData []byte
)

func file_storage_v1_storage_proto_rawDescGZIP() []byte {
	file_storage_v1_storage_proto_rawDescOnce.Do(func() {
		file_storage_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)))
	})
	return file_storage_v1_storage_proto_rawDescData
}

var file_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_storage_v1_storage_proto_goTypes = []any{
	(*InitiateDeliveryRequest)(nil), // 0: api.storage.v1.InitiateDeliveryRequest
	(*InitiateDeliveryReply)(nil),   // 1: api.storage.v1.InitiateDeliveryReply
	(*PickupRequest)(nil),           // 2: api.storage.v1.PickupRequest
	(*PickupReply)(nil),             // 3: api.storage.v1.PickupReply
	(*ConfirmPickupRequest)(nil),    // 4: api.storage.v1.ConfirmPickupRequest
	(*ConfirmPickupReply)(nil),      // 5: api.storage.v1.ConfirmPickupReply
	(*InitiateShipmentRequest)(nil), // 6: api.storage.v1.InitiateShipmentRequest
	(*InitiateShipmentReply)(nil),   // 7: api.storage.v1.InitiateShipmentReply
	(*InitiateStorageRequest)(nil),  // 8: api.storage.v1.InitiateStorageRequest
	(*InitiateStorageReply)(nil),    // 9: api.storage.v1.InitiateStorageReply
	(*RetrieveStorageRequest)(nil),  // 10: api.storage.v1.RetrieveStorageRequest
	(*RetrieveStorageReply)(nil),    // 11: api.storage.v1.RetrieveStorageReply
	(*ConfirmRetrieveRequest)(nil),  // 12: api.storage.v1.ConfirmRetrieveRequest
	(*ConfirmRetrieveReply)(nil),    // 13: api.storage.v1.ConfirmRetrieveReply
	(*TempOpenCellRequest)(nil),     // 14: api.storage.v1.TempOpenCellRequest
	(*TempOpenCellReply)(nil),       // 15: api.storage.v1.TempOpenCellReply
	(*GetOrderRequest)(nil),         // 16: api.storage.v1.GetOrderRequest
	(*GetOrderReply)(nil),           // 17: api.storage.v1.GetOrderReply
	(*ListMyOrdersRequest)(nil),     // 18: api.storage.v1.ListMyOrdersRequest
	(*OrderItem)(nil),               // 19: api.storage.v1.OrderItem
	(*ListMyOrdersReply)(nil),       // 20: api.storage.v1.ListMyOrdersReply
	(*ListCabinetsRequest)(nil),     // 21: api.storage.v1.ListCabinetsRequest
	(*CabinetItem)(nil),             // 22: api.storage.v1.CabinetItem
	(*ListCabinetsReply)(nil),       // 23: api.storage.v1.ListCabinetsReply
	(*GetCabinetDetailRequest)(nil), // 24: api.storage.v1.GetCabinetDetailRequest
	(*GetCabinetDetailReply)(nil),   // 25: api.storage.v1.GetCabinetDetailReply
	(*CellDetail)(nil),              // 26: api.storage.v1.CellDetail
	(*ForceOpenCellRequest)(nil),    // 27: api.storage.v1.ForceOpenCellRequest
	(*ForceOpenCellReply)(nil),      // 28: api.storage.v1.ForceOpenCellReply
}
var file_storage_v1_storage_proto_depIdxs = []int32{
	19, // 0: api.storage.v1.ListMyOrdersReply.items:type_name -> api.storage.v1.OrderItem
	22, // 1: api.storage.v1.ListCabinetsReply.items:type_name -> api.storage.v1.CabinetItem
	26, // 2: api.storage.v1.GetCabinetDetailReply.cells:type_name -> api.storage.v1.CellDetail
	0,  // 3: api.storage.v1.StorageService.InitiateDelivery:input_type -> api.storage.v1.InitiateDeliveryRequest
	2,  // 4: api.storage.v1.StorageService.Pickup:input_type -> api.storage.v1.PickupRequest
	4,  // 5: api.storage.v1.StorageService.ConfirmPickup:input_type -> api.storage.v1.ConfirmPickupRequest
	6,  // 6: api.storage.v1.StorageService.InitiateShipment:input_type -> api.storage.v1.InitiateShipmentRequest
	8,  // 7: api.storage.v1.StorageService.InitiateStorage:input_type -> api.storage.v1.InitiateStorageRequest
	10, // 8: api.storage.v1.StorageService.RetrieveStorage:input_type -> api.storage.v1.RetrieveStorageRequest
	12, // 9: api.storage.v1.StorageService.ConfirmRetrieve:input_type -> api.storage.v1.ConfirmRetrieveRequest
	14, // 10: api.storage.v1.StorageService.TempOpenCell:input_type -> api.storage.v1.TempOpenCellRequest
	16, // 11: api.storage.v1.StorageService.GetOrder:input_type -> api.storage.v1.GetOrderRequest
	18, // 12: api.storage.v1.StorageService.ListMyOrders:input_type -> api.storage.v1.ListMyOrdersRequest
	21, // 13: api.storage.v1.StorageService.ListCabinets:input_type -> api.storage.v1.ListCabinetsRequest
	24, // 14: api.storage.v1.StorageService.GetCabinetDetail:input_type -> api.storage.v1.GetCabinetDetailRequest
	27, // 15: api.storage.v1.StorageService.ForceOpenCell:input_type -> api.storage.v1.ForceOpenCellRequest
	1,  // 16: api.storage.v1.StorageService.InitiateDelivery:output_type -> api.storage.v1.InitiateDeliveryReply
	3,  // 17: api.storage.v1.StorageService.Pickup:output_type -> api.storage.v1.PickupReply
	5,  // 18: api.storage.v1.StorageService.ConfirmPickup:output_type -> api.storage.v1.ConfirmPickupReply
	7,  // 19: api.storage.v1.StorageService.InitiateShipment:output_type -> api.storage.v1.InitiateShipmentReply
	9,  // 20: api.storage.v1.StorageService.InitiateStorage:output_type -> api.storage.v1.InitiateStorageReply
	11, // 21: api.storage.v1.StorageService.RetrieveStorage:output_type -> api.storage.v1.RetrieveStorageReply
	13, // 22: api.storage.v1.StorageService.ConfirmRetrieve:output_type -> api.storage.v1.ConfirmRetrieveReply
	15, // 23: api.storage.v1.StorageService.TempOpenCell:output_type -> api.storage.v1.TempOpenCellReply
	17, // 24: api.storage.v1.StorageService.GetOrder:output_type -> api.storage.v1.GetOrderReply
	20, // 25: api.storage.v1.StorageService.ListMyOrders:output_type -> api.storage.v1.ListMyOrdersReply
	23, // 26: api.storage.v1.StorageService.ListCabinets:output_type -> api.storage.v1.ListCabinetsReply
	25, // 27: api.storage.v1.StorageService.GetCabinetDetail:output_type -> api.storage.v1.GetCabinetDetailReply
	28, // 28: api.storage.v1.StorageService.ForceOpenCell:output_type -> api.storage.v1.ForceOpenCellReply
	16, // [16:29] is the sub-list for method output_type
	3,  // [3:16] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_storage_v1_storage_proto_init() }
func file_storage_v1_storage_proto_init() {
	if File_storage_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_storage_v1_storage_proto_depIdxs,
		MessageInfos:      file_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_storage_v1_storage_proto = out.File
	file_storage_v1_storage_proto_goTypes = nil
	file_storage_v1_storage_proto_depIdxs = nil
}
