authentication {
  backend = "jwt"
  mechanism = "jwt"
  jwt {
    algorithm = "hmac-based"
    secret = "device-service-access-secret-key"
    secret_base64_encoded = false
    verify_claims = {
      device_id = "${device_id}"
      tenant_id = "${tenant_id}"
    }
  }
}
