// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"shared-device-saas/app/user/internal/biz"
	"shared-device-saas/app/user/internal/conf"
	"shared-device-saas/app/user/internal/data"
	"shared-device-saas/app/user/internal/server"
	"shared-device-saas/app/user/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger) // 创建数据访问层
		if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, confData, logger)  // 创建用户仓储
	client, cleanup2, err := data.NewRedisClient(confData, logger) // 创建 Redis 客户端
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	ihuyiClient := data.NewSMSClient(confData, logger) // 创建短信客户端
	jwtManager := biz.NewJWTManager(confData, logger) // 创建 JWT 管理器
	userUsecase := biz.NewUserUsecase(userRepo, client, ihuyiClient, jwtManager, logger) // 创建用户用例
	userService := service.NewUserService(userUsecase) // 创建用户服务
	grpcServer := server.NewGRPCServer(confServer, userService, logger) // 创建 GRPC 服务器
		if err != nil {
		return nil, nil, err
	}
		blacklist := data.NewRedisBlacklist(client, logger) // 创建 Redis 黑名单
		httpServer := server.NewHTTPServer(confServer, userService, jwtManager, blacklist, logger) // 创建 HTTP 服务器
	app := newApp(logger, grpcServer, httpServer) // 创建 Kratos 应用
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
